ALTER TABLE report_cards
ADD COLUMN IF NOT EXISTS total_credits INTEGER,
ADD COLUMN IF NOT EXISTS attendance INTEGER,
ADD COLUMN IF NOT EXISTS comments TEXT,
ADD COLUMN IF NOT EXISTS generated_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS published_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE report_card_details
ADD COLUMN IF NOT EXISTS credit INTEGER;
