// Code generated by MockGen. DO NOT EDIT.
// Source: services/admission-service/internal/domain/usecase/admission_period_usecase.go
//
// Generated by this command:
//
//	mockgen -source=services/admission-service/internal/domain/usecase/admission_period_usecase.go -destination=services/admission-service/internal/domain/mocks/admission_period_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/admission-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAdmissionPeriodUseCase is a mock of AdmissionPeriodUseCase interface.
type MockAdmissionPeriodUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAdmissionPeriodUseCaseMockRecorder
	isgomock struct{}
}

// MockAdmissionPeriodUseCaseMockRecorder is the mock recorder for MockAdmissionPeriodUseCase.
type MockAdmissionPeriodUseCaseMockRecorder struct {
	mock *MockAdmissionPeriodUseCase
}

// NewMockAdmissionPeriodUseCase creates a new mock instance.
func NewMockAdmissionPeriodUseCase(ctrl *gomock.Controller) *MockAdmissionPeriodUseCase {
	mock := &MockAdmissionPeriodUseCase{ctrl: ctrl}
	mock.recorder = &MockAdmissionPeriodUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdmissionPeriodUseCase) EXPECT() *MockAdmissionPeriodUseCaseMockRecorder {
	return m.recorder
}

// AnnounceResults mocks base method.
func (m *MockAdmissionPeriodUseCase) AnnounceResults(ctx context.Context, id uuid.UUID, passingGrade float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AnnounceResults", ctx, id, passingGrade)
	ret0, _ := ret[0].(error)
	return ret0
}

// AnnounceResults indicates an expected call of AnnounceResults.
func (mr *MockAdmissionPeriodUseCaseMockRecorder) AnnounceResults(ctx, id, passingGrade any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AnnounceResults", reflect.TypeOf((*MockAdmissionPeriodUseCase)(nil).AnnounceResults), ctx, id, passingGrade)
}

// Create mocks base method.
func (m *MockAdmissionPeriodUseCase) Create(ctx context.Context, period *entity.AdmissionPeriod) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, period)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAdmissionPeriodUseCaseMockRecorder) Create(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdmissionPeriodUseCase)(nil).Create), ctx, period)
}

// Delete mocks base method.
func (m *MockAdmissionPeriodUseCase) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdmissionPeriodUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdmissionPeriodUseCase)(nil).Delete), ctx, id)
}

// GetActive mocks base method.
func (m *MockAdmissionPeriodUseCase) GetActive(ctx context.Context) (*entity.AdmissionPeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActive", ctx)
	ret0, _ := ret[0].(*entity.AdmissionPeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActive indicates an expected call of GetActive.
func (mr *MockAdmissionPeriodUseCaseMockRecorder) GetActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActive", reflect.TypeOf((*MockAdmissionPeriodUseCase)(nil).GetActive), ctx)
}

// GetByID mocks base method.
func (m *MockAdmissionPeriodUseCase) GetByID(ctx context.Context, id uuid.UUID) (*entity.AdmissionPeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.AdmissionPeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAdmissionPeriodUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAdmissionPeriodUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockAdmissionPeriodUseCase) List(ctx context.Context) ([]*entity.AdmissionPeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.AdmissionPeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAdmissionPeriodUseCaseMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAdmissionPeriodUseCase)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockAdmissionPeriodUseCase) Update(ctx context.Context, period *entity.AdmissionPeriod) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, period)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAdmissionPeriodUseCaseMockRecorder) Update(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdmissionPeriodUseCase)(nil).Update), ctx, period)
}
