// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/admission_period_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/admission_period_repository.go -destination=internal/domain/mocks/admission_period_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/admission-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAdmissionPeriodRepository is a mock of AdmissionPeriodRepository interface.
type MockAdmissionPeriodRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdmissionPeriodRepositoryMockRecorder
	isgomock struct{}
}

// MockAdmissionPeriodRepositoryMockRecorder is the mock recorder for MockAdmissionPeriodRepository.
type MockAdmissionPeriodRepositoryMockRecorder struct {
	mock *MockAdmissionPeriodRepository
}

// NewMockAdmissionPeriodRepository creates a new mock instance.
func NewMockAdmissionPeriodRepository(ctrl *gomock.Controller) *MockAdmissionPeriodRepository {
	mock := &MockAdmissionPeriodRepository{ctrl: ctrl}
	mock.recorder = &MockAdmissionPeriodRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdmissionPeriodRepository) EXPECT() *MockAdmissionPeriodRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdmissionPeriodRepository) Create(ctx context.Context, period *entity.AdmissionPeriod) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, period)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAdmissionPeriodRepositoryMockRecorder) Create(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdmissionPeriodRepository)(nil).Create), ctx, period)
}

// Delete mocks base method.
func (m *MockAdmissionPeriodRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdmissionPeriodRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdmissionPeriodRepository)(nil).Delete), ctx, id)
}

// GetActive mocks base method.
func (m *MockAdmissionPeriodRepository) GetActive(ctx context.Context) (*entity.AdmissionPeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActive", ctx)
	ret0, _ := ret[0].(*entity.AdmissionPeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActive indicates an expected call of GetActive.
func (mr *MockAdmissionPeriodRepositoryMockRecorder) GetActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActive", reflect.TypeOf((*MockAdmissionPeriodRepository)(nil).GetActive), ctx)
}

// GetByID mocks base method.
func (m *MockAdmissionPeriodRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.AdmissionPeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.AdmissionPeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAdmissionPeriodRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAdmissionPeriodRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockAdmissionPeriodRepository) List(ctx context.Context) ([]*entity.AdmissionPeriod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.AdmissionPeriod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAdmissionPeriodRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAdmissionPeriodRepository)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockAdmissionPeriodRepository) Update(ctx context.Context, period *entity.AdmissionPeriod) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, period)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAdmissionPeriodRepositoryMockRecorder) Update(ctx, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdmissionPeriodRepository)(nil).Update), ctx, period)
}
