// Code generated by MockGen. DO NOT EDIT.
// Source: services/admission-service/internal/domain/repository/application_document_repository.go
//
// Generated by this command:
//
//	mockgen -source=services/admission-service/internal/domain/repository/application_document_repository.go -destination=services/admission-service/internal/domain/mocks/application_document_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/admission-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockApplicationDocumentRepository is a mock of ApplicationDocumentRepository interface.
type MockApplicationDocumentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationDocumentRepositoryMockRecorder
	isgomock struct{}
}

// MockApplicationDocumentRepositoryMockRecorder is the mock recorder for MockApplicationDocumentRepository.
type MockApplicationDocumentRepositoryMockRecorder struct {
	mock *MockApplicationDocumentRepository
}

// NewMockApplicationDocumentRepository creates a new mock instance.
func NewMockApplicationDocumentRepository(ctrl *gomock.Controller) *MockApplicationDocumentRepository {
	mock := &MockApplicationDocumentRepository{ctrl: ctrl}
	mock.recorder = &MockApplicationDocumentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationDocumentRepository) EXPECT() *MockApplicationDocumentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockApplicationDocumentRepository) Create(ctx context.Context, doc *entity.ApplicationDocument) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, doc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApplicationDocumentRepositoryMockRecorder) Create(ctx, doc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApplicationDocumentRepository)(nil).Create), ctx, doc)
}

// Delete mocks base method.
func (m *MockApplicationDocumentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockApplicationDocumentRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApplicationDocumentRepository)(nil).Delete), ctx, id)
}

// GetByApplicationID mocks base method.
func (m *MockApplicationDocumentRepository) GetByApplicationID(ctx context.Context, applicationID uuid.UUID) ([]*entity.ApplicationDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByApplicationID", ctx, applicationID)
	ret0, _ := ret[0].([]*entity.ApplicationDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByApplicationID indicates an expected call of GetByApplicationID.
func (mr *MockApplicationDocumentRepositoryMockRecorder) GetByApplicationID(ctx, applicationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByApplicationID", reflect.TypeOf((*MockApplicationDocumentRepository)(nil).GetByApplicationID), ctx, applicationID)
}

// GetByID mocks base method.
func (m *MockApplicationDocumentRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.ApplicationDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.ApplicationDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockApplicationDocumentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockApplicationDocumentRepository)(nil).GetByID), ctx, id)
}
