// Code generated by MockGen. DO NOT EDIT.
// Source: services/notification-service/internal/usecase/notification_usecase.go
//
// Generated by this command:
//
//	mockgen -source=services/notification-service/internal/usecase/notification_usecase.go -destination=services/notification-service/internal/usecase/mocks/notification_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/notification-service/internal/domain/entity"
	usecase "github.com/jjaenal/sisfo-akademik-backend/services/notification-service/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationUseCase is a mock of NotificationUseCase interface.
type MockNotificationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationUseCaseMockRecorder
	isgomock struct{}
}

// MockNotificationUseCaseMockRecorder is the mock recorder for MockNotificationUseCase.
type MockNotificationUseCaseMockRecorder struct {
	mock *MockNotificationUseCase
}

// NewMockNotificationUseCase creates a new mock instance.
func NewMockNotificationUseCase(ctrl *gomock.Controller) *MockNotificationUseCase {
	mock := &MockNotificationUseCase{ctrl: ctrl}
	mock.recorder = &MockNotificationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationUseCase) EXPECT() *MockNotificationUseCaseMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockNotificationUseCase) GetByID(ctx context.Context, id uuid.UUID) (*entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockNotificationUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockNotificationUseCase)(nil).GetByID), ctx, id)
}

// ListByRecipient mocks base method.
func (m *MockNotificationUseCase) ListByRecipient(ctx context.Context, recipient string) ([]*entity.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRecipient", ctx, recipient)
	ret0, _ := ret[0].([]*entity.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByRecipient indicates an expected call of ListByRecipient.
func (mr *MockNotificationUseCaseMockRecorder) ListByRecipient(ctx, recipient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRecipient", reflect.TypeOf((*MockNotificationUseCase)(nil).ListByRecipient), ctx, recipient)
}

// Process mocks base method.
func (m *MockNotificationUseCase) Process(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockNotificationUseCaseMockRecorder) Process(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockNotificationUseCase)(nil).Process), ctx, id)
}

// Send mocks base method.
func (m *MockNotificationUseCase) Send(ctx context.Context, req *usecase.SendNotificationRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockNotificationUseCaseMockRecorder) Send(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockNotificationUseCase)(nil).Send), ctx, req)
}

// UpdateStatus mocks base method.
func (m *MockNotificationUseCase) UpdateStatus(ctx context.Context, id uuid.UUID, status entity.NotificationStatus, errorMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockNotificationUseCaseMockRecorder) UpdateStatus(ctx, id, status, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockNotificationUseCase)(nil).UpdateStatus), ctx, id, status, errorMessage)
}
