// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/notification_template_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/notification_template_usecase.go -destination=internal/usecase/mocks/notification_template_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/notification-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationTemplateUseCase is a mock of NotificationTemplateUseCase interface.
type MockNotificationTemplateUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationTemplateUseCaseMockRecorder
	isgomock struct{}
}

// MockNotificationTemplateUseCaseMockRecorder is the mock recorder for MockNotificationTemplateUseCase.
type MockNotificationTemplateUseCaseMockRecorder struct {
	mock *MockNotificationTemplateUseCase
}

// NewMockNotificationTemplateUseCase creates a new mock instance.
func NewMockNotificationTemplateUseCase(ctrl *gomock.Controller) *MockNotificationTemplateUseCase {
	mock := &MockNotificationTemplateUseCase{ctrl: ctrl}
	mock.recorder = &MockNotificationTemplateUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationTemplateUseCase) EXPECT() *MockNotificationTemplateUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNotificationTemplateUseCase) Create(ctx context.Context, template *entity.NotificationTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationTemplateUseCaseMockRecorder) Create(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationTemplateUseCase)(nil).Create), ctx, template)
}

// Delete mocks base method.
func (m *MockNotificationTemplateUseCase) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNotificationTemplateUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotificationTemplateUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockNotificationTemplateUseCase) GetByID(ctx context.Context, id uuid.UUID) (*entity.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockNotificationTemplateUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockNotificationTemplateUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockNotificationTemplateUseCase) List(ctx context.Context) ([]*entity.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNotificationTemplateUseCaseMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNotificationTemplateUseCase)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockNotificationTemplateUseCase) Update(ctx context.Context, template *entity.NotificationTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNotificationTemplateUseCaseMockRecorder) Update(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNotificationTemplateUseCase)(nil).Update), ctx, template)
}
