// Code generated by MockGen. DO NOT EDIT.
// Source: services/attendance-service/internal/domain/service/school_service.go
//
// Generated by this command:
//
//	mockgen -source=services/attendance-service/internal/domain/service/school_service.go -destination=services/attendance-service/internal/domain/mocks/school_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/jjaenal/sisfo-akademik-backend/services/attendance-service/internal/domain/service"
	gomock "go.uber.org/mock/gomock"
)

// MockSchoolService is a mock of SchoolService interface.
type MockSchoolService struct {
	ctrl     *gomock.Controller
	recorder *MockSchoolServiceMockRecorder
	isgomock struct{}
}

// MockSchoolServiceMockRecorder is the mock recorder for MockSchoolService.
type MockSchoolServiceMockRecorder struct {
	mock *MockSchoolService
}

// NewMockSchoolService creates a new mock instance.
func NewMockSchoolService(ctrl *gomock.Controller) *MockSchoolService {
	mock := &MockSchoolService{ctrl: ctrl}
	mock.recorder = &MockSchoolServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchoolService) EXPECT() *MockSchoolServiceMockRecorder {
	return m.recorder
}

// GetLocation mocks base method.
func (m *MockSchoolService) GetLocation(ctx context.Context, tenantID string) (*service.SchoolLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocation", ctx, tenantID)
	ret0, _ := ret[0].(*service.SchoolLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocation indicates an expected call of GetLocation.
func (mr *MockSchoolServiceMockRecorder) GetLocation(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocation", reflect.TypeOf((*MockSchoolService)(nil).GetLocation), ctx, tenantID)
}
