// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/student_attendance_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/student_attendance_repository.go -destination=internal/domain/mocks/student_attendance_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/attendance-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockStudentAttendanceRepository is a mock of StudentAttendanceRepository interface.
type MockStudentAttendanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStudentAttendanceRepositoryMockRecorder
	isgomock struct{}
}

// MockStudentAttendanceRepositoryMockRecorder is the mock recorder for MockStudentAttendanceRepository.
type MockStudentAttendanceRepositoryMockRecorder struct {
	mock *MockStudentAttendanceRepository
}

// NewMockStudentAttendanceRepository creates a new mock instance.
func NewMockStudentAttendanceRepository(ctrl *gomock.Controller) *MockStudentAttendanceRepository {
	mock := &MockStudentAttendanceRepository{ctrl: ctrl}
	mock.recorder = &MockStudentAttendanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentAttendanceRepository) EXPECT() *MockStudentAttendanceRepositoryMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockStudentAttendanceRepository) BulkCreate(ctx context.Context, attendances []*entity.StudentAttendance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, attendances)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockStudentAttendanceRepositoryMockRecorder) BulkCreate(ctx, attendances any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockStudentAttendanceRepository)(nil).BulkCreate), ctx, attendances)
}

// Create mocks base method.
func (m *MockStudentAttendanceRepository) Create(ctx context.Context, attendance *entity.StudentAttendance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, attendance)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStudentAttendanceRepositoryMockRecorder) Create(ctx, attendance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStudentAttendanceRepository)(nil).Create), ctx, attendance)
}

// GetByClassAndDate mocks base method.
func (m *MockStudentAttendanceRepository) GetByClassAndDate(ctx context.Context, classID uuid.UUID, date time.Time) ([]*entity.StudentAttendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByClassAndDate", ctx, classID, date)
	ret0, _ := ret[0].([]*entity.StudentAttendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByClassAndDate indicates an expected call of GetByClassAndDate.
func (mr *MockStudentAttendanceRepositoryMockRecorder) GetByClassAndDate(ctx, classID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByClassAndDate", reflect.TypeOf((*MockStudentAttendanceRepository)(nil).GetByClassAndDate), ctx, classID, date)
}

// GetByDateRange mocks base method.
func (m *MockStudentAttendanceRepository) GetByDateRange(ctx context.Context, tenantID uuid.UUID, startDate, endDate time.Time, classID *uuid.UUID) ([]*entity.StudentAttendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDateRange", ctx, tenantID, startDate, endDate, classID)
	ret0, _ := ret[0].([]*entity.StudentAttendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDateRange indicates an expected call of GetByDateRange.
func (mr *MockStudentAttendanceRepositoryMockRecorder) GetByDateRange(ctx, tenantID, startDate, endDate, classID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDateRange", reflect.TypeOf((*MockStudentAttendanceRepository)(nil).GetByDateRange), ctx, tenantID, startDate, endDate, classID)
}

// GetByID mocks base method.
func (m *MockStudentAttendanceRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.StudentAttendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.StudentAttendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockStudentAttendanceRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockStudentAttendanceRepository)(nil).GetByID), ctx, id)
}

// GetByTenantAndDate mocks base method.
func (m *MockStudentAttendanceRepository) GetByTenantAndDate(ctx context.Context, tenantID uuid.UUID, date time.Time) ([]*entity.StudentAttendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTenantAndDate", ctx, tenantID, date)
	ret0, _ := ret[0].([]*entity.StudentAttendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTenantAndDate indicates an expected call of GetByTenantAndDate.
func (mr *MockStudentAttendanceRepositoryMockRecorder) GetByTenantAndDate(ctx, tenantID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTenantAndDate", reflect.TypeOf((*MockStudentAttendanceRepository)(nil).GetByTenantAndDate), ctx, tenantID, date)
}

// GetSummary mocks base method.
func (m *MockStudentAttendanceRepository) GetSummary(ctx context.Context, studentID, semesterID uuid.UUID) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, studentID, semesterID)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockStudentAttendanceRepositoryMockRecorder) GetSummary(ctx, studentID, semesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockStudentAttendanceRepository)(nil).GetSummary), ctx, studentID, semesterID)
}

// Update mocks base method.
func (m *MockStudentAttendanceRepository) Update(ctx context.Context, attendance *entity.StudentAttendance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, attendance)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStudentAttendanceRepositoryMockRecorder) Update(ctx, attendance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStudentAttendanceRepository)(nil).Update), ctx, attendance)
}
