// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/student_attendance_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/student_attendance_usecase.go -destination=internal/domain/mocks/student_attendance_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/attendance-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockStudentAttendanceUseCase is a mock of StudentAttendanceUseCase interface.
type MockStudentAttendanceUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockStudentAttendanceUseCaseMockRecorder
	isgomock struct{}
}

// MockStudentAttendanceUseCaseMockRecorder is the mock recorder for MockStudentAttendanceUseCase.
type MockStudentAttendanceUseCaseMockRecorder struct {
	mock *MockStudentAttendanceUseCase
}

// NewMockStudentAttendanceUseCase creates a new mock instance.
func NewMockStudentAttendanceUseCase(ctrl *gomock.Controller) *MockStudentAttendanceUseCase {
	mock := &MockStudentAttendanceUseCase{ctrl: ctrl}
	mock.recorder = &MockStudentAttendanceUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentAttendanceUseCase) EXPECT() *MockStudentAttendanceUseCaseMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockStudentAttendanceUseCase) BulkCreate(ctx context.Context, attendances []*entity.StudentAttendance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, attendances)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockStudentAttendanceUseCaseMockRecorder) BulkCreate(ctx, attendances any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockStudentAttendanceUseCase)(nil).BulkCreate), ctx, attendances)
}

// Create mocks base method.
func (m *MockStudentAttendanceUseCase) Create(ctx context.Context, attendance *entity.StudentAttendance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, attendance)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStudentAttendanceUseCaseMockRecorder) Create(ctx, attendance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStudentAttendanceUseCase)(nil).Create), ctx, attendance)
}

// GetByClassAndDate mocks base method.
func (m *MockStudentAttendanceUseCase) GetByClassAndDate(ctx context.Context, classID uuid.UUID, date time.Time) ([]*entity.StudentAttendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByClassAndDate", ctx, classID, date)
	ret0, _ := ret[0].([]*entity.StudentAttendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByClassAndDate indicates an expected call of GetByClassAndDate.
func (mr *MockStudentAttendanceUseCaseMockRecorder) GetByClassAndDate(ctx, classID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByClassAndDate", reflect.TypeOf((*MockStudentAttendanceUseCase)(nil).GetByClassAndDate), ctx, classID, date)
}

// GetByID mocks base method.
func (m *MockStudentAttendanceUseCase) GetByID(ctx context.Context, id uuid.UUID) (*entity.StudentAttendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.StudentAttendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockStudentAttendanceUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockStudentAttendanceUseCase)(nil).GetByID), ctx, id)
}

// GetSummary mocks base method.
func (m *MockStudentAttendanceUseCase) GetSummary(ctx context.Context, studentID, semesterID uuid.UUID) (map[string]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, studentID, semesterID)
	ret0, _ := ret[0].(map[string]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockStudentAttendanceUseCaseMockRecorder) GetSummary(ctx, studentID, semesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockStudentAttendanceUseCase)(nil).GetSummary), ctx, studentID, semesterID)
}

// Update mocks base method.
func (m *MockStudentAttendanceUseCase) Update(ctx context.Context, attendance *entity.StudentAttendance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, attendance)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStudentAttendanceUseCaseMockRecorder) Update(ctx, attendance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStudentAttendanceUseCase)(nil).Update), ctx, attendance)
}
