// Code generated by MockGen. DO NOT EDIT.
// Source: services/attendance-service/internal/domain/usecase/teacher_attendance_usecase.go
//
// Generated by this command:
//
//	mockgen -source=services/attendance-service/internal/domain/usecase/teacher_attendance_usecase.go -destination=services/attendance-service/internal/domain/mocks/teacher_attendance_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/attendance-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTeacherAttendanceUseCase is a mock of TeacherAttendanceUseCase interface.
type MockTeacherAttendanceUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTeacherAttendanceUseCaseMockRecorder
	isgomock struct{}
}

// MockTeacherAttendanceUseCaseMockRecorder is the mock recorder for MockTeacherAttendanceUseCase.
type MockTeacherAttendanceUseCaseMockRecorder struct {
	mock *MockTeacherAttendanceUseCase
}

// NewMockTeacherAttendanceUseCase creates a new mock instance.
func NewMockTeacherAttendanceUseCase(ctrl *gomock.Controller) *MockTeacherAttendanceUseCase {
	mock := &MockTeacherAttendanceUseCase{ctrl: ctrl}
	mock.recorder = &MockTeacherAttendanceUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeacherAttendanceUseCase) EXPECT() *MockTeacherAttendanceUseCaseMockRecorder {
	return m.recorder
}

// CheckIn mocks base method.
func (m *MockTeacherAttendanceUseCase) CheckIn(ctx context.Context, attendance *entity.TeacherAttendance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIn", ctx, attendance)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckIn indicates an expected call of CheckIn.
func (mr *MockTeacherAttendanceUseCaseMockRecorder) CheckIn(ctx, attendance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIn", reflect.TypeOf((*MockTeacherAttendanceUseCase)(nil).CheckIn), ctx, attendance)
}

// CheckOut mocks base method.
func (m *MockTeacherAttendanceUseCase) CheckOut(ctx context.Context, teacherID uuid.UUID, date, checkOutTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOut", ctx, teacherID, date, checkOutTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckOut indicates an expected call of CheckOut.
func (mr *MockTeacherAttendanceUseCaseMockRecorder) CheckOut(ctx, teacherID, date, checkOutTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOut", reflect.TypeOf((*MockTeacherAttendanceUseCase)(nil).CheckOut), ctx, teacherID, date, checkOutTime)
}

// GetByTeacherAndDate mocks base method.
func (m *MockTeacherAttendanceUseCase) GetByTeacherAndDate(ctx context.Context, teacherID uuid.UUID, date time.Time) (*entity.TeacherAttendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTeacherAndDate", ctx, teacherID, date)
	ret0, _ := ret[0].(*entity.TeacherAttendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTeacherAndDate indicates an expected call of GetByTeacherAndDate.
func (mr *MockTeacherAttendanceUseCaseMockRecorder) GetByTeacherAndDate(ctx, teacherID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTeacherAndDate", reflect.TypeOf((*MockTeacherAttendanceUseCase)(nil).GetByTeacherAndDate), ctx, teacherID, date)
}

// List mocks base method.
func (m *MockTeacherAttendanceUseCase) List(ctx context.Context, filter map[string]any) ([]*entity.TeacherAttendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*entity.TeacherAttendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTeacherAttendanceUseCaseMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTeacherAttendanceUseCase)(nil).List), ctx, filter)
}
