// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/academic_year_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/academic_year_repository.go -destination=internal/domain/mocks/academic_year_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAcademicYearRepository is a mock of AcademicYearRepository interface.
type MockAcademicYearRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAcademicYearRepositoryMockRecorder
	isgomock struct{}
}

// MockAcademicYearRepositoryMockRecorder is the mock recorder for MockAcademicYearRepository.
type MockAcademicYearRepositoryMockRecorder struct {
	mock *MockAcademicYearRepository
}

// NewMockAcademicYearRepository creates a new mock instance.
func NewMockAcademicYearRepository(ctrl *gomock.Controller) *MockAcademicYearRepository {
	mock := &MockAcademicYearRepository{ctrl: ctrl}
	mock.recorder = &MockAcademicYearRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAcademicYearRepository) EXPECT() *MockAcademicYearRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAcademicYearRepository) Create(ctx context.Context, academicYear *entity.AcademicYear) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, academicYear)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAcademicYearRepositoryMockRecorder) Create(ctx, academicYear any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAcademicYearRepository)(nil).Create), ctx, academicYear)
}

// Delete mocks base method.
func (m *MockAcademicYearRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAcademicYearRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAcademicYearRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockAcademicYearRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.AcademicYear, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.AcademicYear)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAcademicYearRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAcademicYearRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockAcademicYearRepository) List(ctx context.Context, tenantID string) ([]entity.AcademicYear, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID)
	ret0, _ := ret[0].([]entity.AcademicYear)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAcademicYearRepositoryMockRecorder) List(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAcademicYearRepository)(nil).List), ctx, tenantID)
}

// Update mocks base method.
func (m *MockAcademicYearRepository) Update(ctx context.Context, academicYear *entity.AcademicYear) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, academicYear)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAcademicYearRepositoryMockRecorder) Update(ctx, academicYear any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAcademicYearRepository)(nil).Update), ctx, academicYear)
}
