// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/class_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/class_repository.go -destination=internal/domain/mocks/class_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockClassRepository is a mock of ClassRepository interface.
type MockClassRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClassRepositoryMockRecorder
	isgomock struct{}
}

// MockClassRepositoryMockRecorder is the mock recorder for MockClassRepository.
type MockClassRepositoryMockRecorder struct {
	mock *MockClassRepository
}

// NewMockClassRepository creates a new mock instance.
func NewMockClassRepository(ctrl *gomock.Controller) *MockClassRepository {
	mock := &MockClassRepository{ctrl: ctrl}
	mock.recorder = &MockClassRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClassRepository) EXPECT() *MockClassRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClassRepository) Create(ctx context.Context, class *entity.Class) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, class)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockClassRepositoryMockRecorder) Create(ctx, class any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClassRepository)(nil).Create), ctx, class)
}

// Delete mocks base method.
func (m *MockClassRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClassRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClassRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockClassRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Class, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Class)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockClassRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockClassRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockClassRepository) List(ctx context.Context, tenantID string, limit, offset int) ([]entity.Class, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID, limit, offset)
	ret0, _ := ret[0].([]entity.Class)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockClassRepositoryMockRecorder) List(ctx, tenantID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClassRepository)(nil).List), ctx, tenantID, limit, offset)
}

// Update mocks base method.
func (m *MockClassRepository) Update(ctx context.Context, class *entity.Class) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, class)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockClassRepositoryMockRecorder) Update(ctx, class any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClassRepository)(nil).Update), ctx, class)
}
