// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/class_subject_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/class_subject_repository.go -destination=internal/domain/mocks/class_subject_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockClassSubjectRepository is a mock of ClassSubjectRepository interface.
type MockClassSubjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClassSubjectRepositoryMockRecorder
	isgomock struct{}
}

// MockClassSubjectRepositoryMockRecorder is the mock recorder for MockClassSubjectRepository.
type MockClassSubjectRepositoryMockRecorder struct {
	mock *MockClassSubjectRepository
}

// NewMockClassSubjectRepository creates a new mock instance.
func NewMockClassSubjectRepository(ctrl *gomock.Controller) *MockClassSubjectRepository {
	mock := &MockClassSubjectRepository{ctrl: ctrl}
	mock.recorder = &MockClassSubjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClassSubjectRepository) EXPECT() *MockClassSubjectRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClassSubjectRepository) Create(ctx context.Context, classSubject *entity.ClassSubject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, classSubject)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockClassSubjectRepositoryMockRecorder) Create(ctx, classSubject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClassSubjectRepository)(nil).Create), ctx, classSubject)
}

// Delete mocks base method.
func (m *MockClassSubjectRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClassSubjectRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClassSubjectRepository)(nil).Delete), ctx, id)
}

// GetByClassAndSubject mocks base method.
func (m *MockClassSubjectRepository) GetByClassAndSubject(ctx context.Context, classID, subjectID uuid.UUID) (*entity.ClassSubject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByClassAndSubject", ctx, classID, subjectID)
	ret0, _ := ret[0].(*entity.ClassSubject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByClassAndSubject indicates an expected call of GetByClassAndSubject.
func (mr *MockClassSubjectRepositoryMockRecorder) GetByClassAndSubject(ctx, classID, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByClassAndSubject", reflect.TypeOf((*MockClassSubjectRepository)(nil).GetByClassAndSubject), ctx, classID, subjectID)
}

// GetByID mocks base method.
func (m *MockClassSubjectRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.ClassSubject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.ClassSubject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockClassSubjectRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockClassSubjectRepository)(nil).GetByID), ctx, id)
}

// ListByClass mocks base method.
func (m *MockClassSubjectRepository) ListByClass(ctx context.Context, classID uuid.UUID) ([]entity.ClassSubject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClass", ctx, classID)
	ret0, _ := ret[0].([]entity.ClassSubject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClass indicates an expected call of ListByClass.
func (mr *MockClassSubjectRepositoryMockRecorder) ListByClass(ctx, classID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClass", reflect.TypeOf((*MockClassSubjectRepository)(nil).ListByClass), ctx, classID)
}

// ListByTeacher mocks base method.
func (m *MockClassSubjectRepository) ListByTeacher(ctx context.Context, teacherID uuid.UUID) ([]entity.ClassSubject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTeacher", ctx, teacherID)
	ret0, _ := ret[0].([]entity.ClassSubject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTeacher indicates an expected call of ListByTeacher.
func (mr *MockClassSubjectRepositoryMockRecorder) ListByTeacher(ctx, teacherID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTeacher", reflect.TypeOf((*MockClassSubjectRepository)(nil).ListByTeacher), ctx, teacherID)
}

// Update mocks base method.
func (m *MockClassSubjectRepository) Update(ctx context.Context, classSubject *entity.ClassSubject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, classSubject)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockClassSubjectRepositoryMockRecorder) Update(ctx, classSubject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClassSubjectRepository)(nil).Update), ctx, classSubject)
}
