// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/class_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/class_usecase.go -destination=internal/domain/mocks/class_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockClassUseCase is a mock of ClassUseCase interface.
type MockClassUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockClassUseCaseMockRecorder
	isgomock struct{}
}

// MockClassUseCaseMockRecorder is the mock recorder for MockClassUseCase.
type MockClassUseCaseMockRecorder struct {
	mock *MockClassUseCase
}

// NewMockClassUseCase creates a new mock instance.
func NewMockClassUseCase(ctrl *gomock.Controller) *MockClassUseCase {
	mock := &MockClassUseCase{ctrl: ctrl}
	mock.recorder = &MockClassUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClassUseCase) EXPECT() *MockClassUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClassUseCase) Create(ctx context.Context, class *entity.Class) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, class)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockClassUseCaseMockRecorder) Create(ctx, class any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClassUseCase)(nil).Create), ctx, class)
}

// Delete mocks base method.
func (m *MockClassUseCase) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClassUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClassUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockClassUseCase) GetByID(ctx context.Context, id uuid.UUID) (*entity.Class, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Class)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockClassUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockClassUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockClassUseCase) List(ctx context.Context, tenantID string, limit, offset int) ([]entity.Class, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID, limit, offset)
	ret0, _ := ret[0].([]entity.Class)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockClassUseCaseMockRecorder) List(ctx, tenantID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClassUseCase)(nil).List), ctx, tenantID, limit, offset)
}

// Update mocks base method.
func (m *MockClassUseCase) Update(ctx context.Context, class *entity.Class) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, class)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockClassUseCaseMockRecorder) Update(ctx, class any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClassUseCase)(nil).Update), ctx, class)
}
