// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/curriculum_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/curriculum_usecase.go -destination=internal/domain/mocks/curriculum_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCurriculumUseCase is a mock of CurriculumUseCase interface.
type MockCurriculumUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCurriculumUseCaseMockRecorder
	isgomock struct{}
}

// MockCurriculumUseCaseMockRecorder is the mock recorder for MockCurriculumUseCase.
type MockCurriculumUseCaseMockRecorder struct {
	mock *MockCurriculumUseCase
}

// NewMockCurriculumUseCase creates a new mock instance.
func NewMockCurriculumUseCase(ctrl *gomock.Controller) *MockCurriculumUseCase {
	mock := &MockCurriculumUseCase{ctrl: ctrl}
	mock.recorder = &MockCurriculumUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurriculumUseCase) EXPECT() *MockCurriculumUseCaseMockRecorder {
	return m.recorder
}

// AddGradingRule mocks base method.
func (m *MockCurriculumUseCase) AddGradingRule(ctx context.Context, rule *entity.GradingRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGradingRule", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGradingRule indicates an expected call of AddGradingRule.
func (mr *MockCurriculumUseCaseMockRecorder) AddGradingRule(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGradingRule", reflect.TypeOf((*MockCurriculumUseCase)(nil).AddGradingRule), ctx, rule)
}

// AddSubject mocks base method.
func (m *MockCurriculumUseCase) AddSubject(ctx context.Context, cs *entity.CurriculumSubject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSubject", ctx, cs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSubject indicates an expected call of AddSubject.
func (mr *MockCurriculumUseCaseMockRecorder) AddSubject(ctx, cs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSubject", reflect.TypeOf((*MockCurriculumUseCase)(nil).AddSubject), ctx, cs)
}

// Create mocks base method.
func (m *MockCurriculumUseCase) Create(ctx context.Context, curriculum *entity.Curriculum) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, curriculum)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCurriculumUseCaseMockRecorder) Create(ctx, curriculum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCurriculumUseCase)(nil).Create), ctx, curriculum)
}

// Delete mocks base method.
func (m *MockCurriculumUseCase) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCurriculumUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCurriculumUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockCurriculumUseCase) GetByID(ctx context.Context, id uuid.UUID) (*entity.Curriculum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Curriculum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCurriculumUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCurriculumUseCase)(nil).GetByID), ctx, id)
}

// GetGradingRules mocks base method.
func (m *MockCurriculumUseCase) GetGradingRules(ctx context.Context, curriculumID uuid.UUID) ([]entity.GradingRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGradingRules", ctx, curriculumID)
	ret0, _ := ret[0].([]entity.GradingRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGradingRules indicates an expected call of GetGradingRules.
func (mr *MockCurriculumUseCaseMockRecorder) GetGradingRules(ctx, curriculumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGradingRules", reflect.TypeOf((*MockCurriculumUseCase)(nil).GetGradingRules), ctx, curriculumID)
}

// List mocks base method.
func (m *MockCurriculumUseCase) List(ctx context.Context, tenantID string, limit, offset int) ([]entity.Curriculum, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID, limit, offset)
	ret0, _ := ret[0].([]entity.Curriculum)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockCurriculumUseCaseMockRecorder) List(ctx, tenantID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCurriculumUseCase)(nil).List), ctx, tenantID, limit, offset)
}

// ListSubjects mocks base method.
func (m *MockCurriculumUseCase) ListSubjects(ctx context.Context, curriculumID uuid.UUID) ([]entity.CurriculumSubject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubjects", ctx, curriculumID)
	ret0, _ := ret[0].([]entity.CurriculumSubject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubjects indicates an expected call of ListSubjects.
func (mr *MockCurriculumUseCaseMockRecorder) ListSubjects(ctx, curriculumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubjects", reflect.TypeOf((*MockCurriculumUseCase)(nil).ListSubjects), ctx, curriculumID)
}

// RemoveSubject mocks base method.
func (m *MockCurriculumUseCase) RemoveSubject(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSubject", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSubject indicates an expected call of RemoveSubject.
func (mr *MockCurriculumUseCaseMockRecorder) RemoveSubject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSubject", reflect.TypeOf((*MockCurriculumUseCase)(nil).RemoveSubject), ctx, id)
}

// Update mocks base method.
func (m *MockCurriculumUseCase) Update(ctx context.Context, curriculum *entity.Curriculum) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, curriculum)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCurriculumUseCaseMockRecorder) Update(ctx, curriculum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCurriculumUseCase)(nil).Update), ctx, curriculum)
}
