// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/curriculum_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/curriculum_repository.go -destination=internal/domain/mocks/curriculum_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCurriculumRepository is a mock of CurriculumRepository interface.
type MockCurriculumRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCurriculumRepositoryMockRecorder
	isgomock struct{}
}

// MockCurriculumRepositoryMockRecorder is the mock recorder for MockCurriculumRepository.
type MockCurriculumRepositoryMockRecorder struct {
	mock *MockCurriculumRepository
}

// NewMockCurriculumRepository creates a new mock instance.
func NewMockCurriculumRepository(ctrl *gomock.Controller) *MockCurriculumRepository {
	mock := &MockCurriculumRepository{ctrl: ctrl}
	mock.recorder = &MockCurriculumRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurriculumRepository) EXPECT() *MockCurriculumRepositoryMockRecorder {
	return m.recorder
}

// AddGradingRule mocks base method.
func (m *MockCurriculumRepository) AddGradingRule(ctx context.Context, rule *entity.GradingRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGradingRule", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGradingRule indicates an expected call of AddGradingRule.
func (mr *MockCurriculumRepositoryMockRecorder) AddGradingRule(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGradingRule", reflect.TypeOf((*MockCurriculumRepository)(nil).AddGradingRule), ctx, rule)
}

// AddSubject mocks base method.
func (m *MockCurriculumRepository) AddSubject(ctx context.Context, cs *entity.CurriculumSubject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSubject", ctx, cs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSubject indicates an expected call of AddSubject.
func (mr *MockCurriculumRepositoryMockRecorder) AddSubject(ctx, cs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSubject", reflect.TypeOf((*MockCurriculumRepository)(nil).AddSubject), ctx, cs)
}

// Create mocks base method.
func (m *MockCurriculumRepository) Create(ctx context.Context, curriculum *entity.Curriculum) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, curriculum)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCurriculumRepositoryMockRecorder) Create(ctx, curriculum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCurriculumRepository)(nil).Create), ctx, curriculum)
}

// Delete mocks base method.
func (m *MockCurriculumRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCurriculumRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCurriculumRepository)(nil).Delete), ctx, id)
}

// DeleteGradingRule mocks base method.
func (m *MockCurriculumRepository) DeleteGradingRule(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGradingRule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGradingRule indicates an expected call of DeleteGradingRule.
func (mr *MockCurriculumRepositoryMockRecorder) DeleteGradingRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGradingRule", reflect.TypeOf((*MockCurriculumRepository)(nil).DeleteGradingRule), ctx, id)
}

// GetByID mocks base method.
func (m *MockCurriculumRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Curriculum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Curriculum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCurriculumRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCurriculumRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockCurriculumRepository) List(ctx context.Context, tenantID string, limit, offset int) ([]entity.Curriculum, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID, limit, offset)
	ret0, _ := ret[0].([]entity.Curriculum)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockCurriculumRepositoryMockRecorder) List(ctx, tenantID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCurriculumRepository)(nil).List), ctx, tenantID, limit, offset)
}

// ListGradingRules mocks base method.
func (m *MockCurriculumRepository) ListGradingRules(ctx context.Context, curriculumID uuid.UUID) ([]entity.GradingRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGradingRules", ctx, curriculumID)
	ret0, _ := ret[0].([]entity.GradingRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGradingRules indicates an expected call of ListGradingRules.
func (mr *MockCurriculumRepositoryMockRecorder) ListGradingRules(ctx, curriculumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGradingRules", reflect.TypeOf((*MockCurriculumRepository)(nil).ListGradingRules), ctx, curriculumID)
}

// ListSubjects mocks base method.
func (m *MockCurriculumRepository) ListSubjects(ctx context.Context, curriculumID uuid.UUID) ([]entity.CurriculumSubject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubjects", ctx, curriculumID)
	ret0, _ := ret[0].([]entity.CurriculumSubject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubjects indicates an expected call of ListSubjects.
func (mr *MockCurriculumRepositoryMockRecorder) ListSubjects(ctx, curriculumID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubjects", reflect.TypeOf((*MockCurriculumRepository)(nil).ListSubjects), ctx, curriculumID)
}

// RemoveSubject mocks base method.
func (m *MockCurriculumRepository) RemoveSubject(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSubject", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSubject indicates an expected call of RemoveSubject.
func (mr *MockCurriculumRepositoryMockRecorder) RemoveSubject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSubject", reflect.TypeOf((*MockCurriculumRepository)(nil).RemoveSubject), ctx, id)
}

// Update mocks base method.
func (m *MockCurriculumRepository) Update(ctx context.Context, curriculum *entity.Curriculum) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, curriculum)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCurriculumRepositoryMockRecorder) Update(ctx, curriculum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCurriculumRepository)(nil).Update), ctx, curriculum)
}
