// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/enrollment_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/enrollment_usecase.go -destination=internal/domain/mocks/enrollment_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockEnrollmentUseCase is a mock of EnrollmentUseCase interface.
type MockEnrollmentUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockEnrollmentUseCaseMockRecorder
	isgomock struct{}
}

// MockEnrollmentUseCaseMockRecorder is the mock recorder for MockEnrollmentUseCase.
type MockEnrollmentUseCaseMockRecorder struct {
	mock *MockEnrollmentUseCase
}

// NewMockEnrollmentUseCase creates a new mock instance.
func NewMockEnrollmentUseCase(ctrl *gomock.Controller) *MockEnrollmentUseCase {
	mock := &MockEnrollmentUseCase{ctrl: ctrl}
	mock.recorder = &MockEnrollmentUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrollmentUseCase) EXPECT() *MockEnrollmentUseCaseMockRecorder {
	return m.recorder
}

// BulkEnroll mocks base method.
func (m *MockEnrollmentUseCase) BulkEnroll(ctx context.Context, classID uuid.UUID, studentIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkEnroll", ctx, classID, studentIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkEnroll indicates an expected call of BulkEnroll.
func (mr *MockEnrollmentUseCaseMockRecorder) BulkEnroll(ctx, classID, studentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkEnroll", reflect.TypeOf((*MockEnrollmentUseCase)(nil).BulkEnroll), ctx, classID, studentIDs)
}

// Enroll mocks base method.
func (m *MockEnrollmentUseCase) Enroll(ctx context.Context, enrollment *entity.Enrollment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enroll", ctx, enrollment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enroll indicates an expected call of Enroll.
func (mr *MockEnrollmentUseCaseMockRecorder) Enroll(ctx, enrollment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enroll", reflect.TypeOf((*MockEnrollmentUseCase)(nil).Enroll), ctx, enrollment)
}

// GetByID mocks base method.
func (m *MockEnrollmentUseCase) GetByID(ctx context.Context, id uuid.UUID) (*entity.Enrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Enrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEnrollmentUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEnrollmentUseCase)(nil).GetByID), ctx, id)
}

// ListByClass mocks base method.
func (m *MockEnrollmentUseCase) ListByClass(ctx context.Context, classID uuid.UUID) ([]entity.Enrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClass", ctx, classID)
	ret0, _ := ret[0].([]entity.Enrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClass indicates an expected call of ListByClass.
func (mr *MockEnrollmentUseCaseMockRecorder) ListByClass(ctx, classID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClass", reflect.TypeOf((*MockEnrollmentUseCase)(nil).ListByClass), ctx, classID)
}

// ListByStudent mocks base method.
func (m *MockEnrollmentUseCase) ListByStudent(ctx context.Context, studentID uuid.UUID) ([]entity.Enrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStudent", ctx, studentID)
	ret0, _ := ret[0].([]entity.Enrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByStudent indicates an expected call of ListByStudent.
func (mr *MockEnrollmentUseCaseMockRecorder) ListByStudent(ctx, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStudent", reflect.TypeOf((*MockEnrollmentUseCase)(nil).ListByStudent), ctx, studentID)
}

// Unenroll mocks base method.
func (m *MockEnrollmentUseCase) Unenroll(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unenroll", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unenroll indicates an expected call of Unenroll.
func (mr *MockEnrollmentUseCaseMockRecorder) Unenroll(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unenroll", reflect.TypeOf((*MockEnrollmentUseCase)(nil).Unenroll), ctx, id)
}

// UpdateStatus mocks base method.
func (m *MockEnrollmentUseCase) UpdateStatus(ctx context.Context, id uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockEnrollmentUseCaseMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockEnrollmentUseCase)(nil).UpdateStatus), ctx, id, status)
}
