// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/enrollment_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/enrollment_repository.go -destination=internal/domain/mocks/enrollment_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockEnrollmentRepository is a mock of EnrollmentRepository interface.
type MockEnrollmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEnrollmentRepositoryMockRecorder
	isgomock struct{}
}

// MockEnrollmentRepositoryMockRecorder is the mock recorder for MockEnrollmentRepository.
type MockEnrollmentRepositoryMockRecorder struct {
	mock *MockEnrollmentRepository
}

// NewMockEnrollmentRepository creates a new mock instance.
func NewMockEnrollmentRepository(ctrl *gomock.Controller) *MockEnrollmentRepository {
	mock := &MockEnrollmentRepository{ctrl: ctrl}
	mock.recorder = &MockEnrollmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrollmentRepository) EXPECT() *MockEnrollmentRepositoryMockRecorder {
	return m.recorder
}

// Enroll mocks base method.
func (m *MockEnrollmentRepository) Enroll(ctx context.Context, enrollment *entity.Enrollment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enroll", ctx, enrollment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enroll indicates an expected call of Enroll.
func (mr *MockEnrollmentRepositoryMockRecorder) Enroll(ctx, enrollment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enroll", reflect.TypeOf((*MockEnrollmentRepository)(nil).Enroll), ctx, enrollment)
}

// GetByID mocks base method.
func (m *MockEnrollmentRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Enrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Enrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockEnrollmentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockEnrollmentRepository)(nil).GetByID), ctx, id)
}

// ListByClass mocks base method.
func (m *MockEnrollmentRepository) ListByClass(ctx context.Context, classID uuid.UUID) ([]entity.Enrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClass", ctx, classID)
	ret0, _ := ret[0].([]entity.Enrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClass indicates an expected call of ListByClass.
func (mr *MockEnrollmentRepositoryMockRecorder) ListByClass(ctx, classID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClass", reflect.TypeOf((*MockEnrollmentRepository)(nil).ListByClass), ctx, classID)
}

// ListByStudent mocks base method.
func (m *MockEnrollmentRepository) ListByStudent(ctx context.Context, studentID uuid.UUID) ([]entity.Enrollment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStudent", ctx, studentID)
	ret0, _ := ret[0].([]entity.Enrollment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByStudent indicates an expected call of ListByStudent.
func (mr *MockEnrollmentRepositoryMockRecorder) ListByStudent(ctx, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStudent", reflect.TypeOf((*MockEnrollmentRepository)(nil).ListByStudent), ctx, studentID)
}

// Unenroll mocks base method.
func (m *MockEnrollmentRepository) Unenroll(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unenroll", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unenroll indicates an expected call of Unenroll.
func (mr *MockEnrollmentRepositoryMockRecorder) Unenroll(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unenroll", reflect.TypeOf((*MockEnrollmentRepository)(nil).Unenroll), ctx, id)
}

// UpdateStatus mocks base method.
func (m *MockEnrollmentRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockEnrollmentRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockEnrollmentRepository)(nil).UpdateStatus), ctx, id, status)
}
