// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/schedule_template_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/schedule_template_repository.go -destination=internal/domain/mocks/schedule_template_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduleTemplateRepository is a mock of ScheduleTemplateRepository interface.
type MockScheduleTemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleTemplateRepositoryMockRecorder
	isgomock struct{}
}

// MockScheduleTemplateRepositoryMockRecorder is the mock recorder for MockScheduleTemplateRepository.
type MockScheduleTemplateRepositoryMockRecorder struct {
	mock *MockScheduleTemplateRepository
}

// NewMockScheduleTemplateRepository creates a new mock instance.
func NewMockScheduleTemplateRepository(ctrl *gomock.Controller) *MockScheduleTemplateRepository {
	mock := &MockScheduleTemplateRepository{ctrl: ctrl}
	mock.recorder = &MockScheduleTemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleTemplateRepository) EXPECT() *MockScheduleTemplateRepositoryMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockScheduleTemplateRepository) AddItem(ctx context.Context, item *entity.ScheduleTemplateItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddItem indicates an expected call of AddItem.
func (mr *MockScheduleTemplateRepositoryMockRecorder) AddItem(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockScheduleTemplateRepository)(nil).AddItem), ctx, item)
}

// Create mocks base method.
func (m *MockScheduleTemplateRepository) Create(ctx context.Context, template *entity.ScheduleTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockScheduleTemplateRepositoryMockRecorder) Create(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScheduleTemplateRepository)(nil).Create), ctx, template)
}

// Delete mocks base method.
func (m *MockScheduleTemplateRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockScheduleTemplateRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockScheduleTemplateRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockScheduleTemplateRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.ScheduleTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.ScheduleTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockScheduleTemplateRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockScheduleTemplateRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockScheduleTemplateRepository) List(ctx context.Context, tenantID string) ([]entity.ScheduleTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID)
	ret0, _ := ret[0].([]entity.ScheduleTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockScheduleTemplateRepositoryMockRecorder) List(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockScheduleTemplateRepository)(nil).List), ctx, tenantID)
}

// ListItems mocks base method.
func (m *MockScheduleTemplateRepository) ListItems(ctx context.Context, templateID uuid.UUID) ([]entity.ScheduleTemplateItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx, templateID)
	ret0, _ := ret[0].([]entity.ScheduleTemplateItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItems indicates an expected call of ListItems.
func (mr *MockScheduleTemplateRepositoryMockRecorder) ListItems(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockScheduleTemplateRepository)(nil).ListItems), ctx, templateID)
}

// RemoveItem mocks base method.
func (m *MockScheduleTemplateRepository) RemoveItem(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveItem", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockScheduleTemplateRepositoryMockRecorder) RemoveItem(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockScheduleTemplateRepository)(nil).RemoveItem), ctx, id)
}

// Update mocks base method.
func (m *MockScheduleTemplateRepository) Update(ctx context.Context, template *entity.ScheduleTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockScheduleTemplateRepositoryMockRecorder) Update(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockScheduleTemplateRepository)(nil).Update), ctx, template)
}
