// Code generated by MockGen. DO NOT EDIT.
// Source: services/academic-service/internal/domain/repository/schedule_repository.go
//
// Generated by this command:
//
//	mockgen -source=services/academic-service/internal/domain/repository/schedule_repository.go -destination=services/academic-service/internal/domain/mocks/schedule_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduleRepository is a mock of ScheduleRepository interface.
type MockScheduleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleRepositoryMockRecorder
	isgomock struct{}
}

// MockScheduleRepositoryMockRecorder is the mock recorder for MockScheduleRepository.
type MockScheduleRepositoryMockRecorder struct {
	mock *MockScheduleRepository
}

// NewMockScheduleRepository creates a new mock instance.
func NewMockScheduleRepository(ctrl *gomock.Controller) *MockScheduleRepository {
	mock := &MockScheduleRepository{ctrl: ctrl}
	mock.recorder = &MockScheduleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleRepository) EXPECT() *MockScheduleRepositoryMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockScheduleRepository) BulkCreate(ctx context.Context, schedules []*entity.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, schedules)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockScheduleRepositoryMockRecorder) BulkCreate(ctx, schedules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockScheduleRepository)(nil).BulkCreate), ctx, schedules)
}

// CheckConflicts mocks base method.
func (m *MockScheduleRepository) CheckConflicts(ctx context.Context, schedule *entity.Schedule) ([]entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckConflicts", ctx, schedule)
	ret0, _ := ret[0].([]entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckConflicts indicates an expected call of CheckConflicts.
func (mr *MockScheduleRepositoryMockRecorder) CheckConflicts(ctx, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckConflicts", reflect.TypeOf((*MockScheduleRepository)(nil).CheckConflicts), ctx, schedule)
}

// Create mocks base method.
func (m *MockScheduleRepository) Create(ctx context.Context, schedule *entity.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockScheduleRepositoryMockRecorder) Create(ctx, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScheduleRepository)(nil).Create), ctx, schedule)
}

// Delete mocks base method.
func (m *MockScheduleRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockScheduleRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockScheduleRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockScheduleRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockScheduleRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockScheduleRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockScheduleRepository) List(ctx context.Context, tenantID string, limit, offset int) ([]entity.Schedule, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID, limit, offset)
	ret0, _ := ret[0].([]entity.Schedule)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockScheduleRepositoryMockRecorder) List(ctx, tenantID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockScheduleRepository)(nil).List), ctx, tenantID, limit, offset)
}

// ListByClass mocks base method.
func (m *MockScheduleRepository) ListByClass(ctx context.Context, classID uuid.UUID) ([]entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClass", ctx, classID)
	ret0, _ := ret[0].([]entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClass indicates an expected call of ListByClass.
func (mr *MockScheduleRepositoryMockRecorder) ListByClass(ctx, classID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClass", reflect.TypeOf((*MockScheduleRepository)(nil).ListByClass), ctx, classID)
}

// Update mocks base method.
func (m *MockScheduleRepository) Update(ctx context.Context, schedule *entity.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockScheduleRepositoryMockRecorder) Update(ctx, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockScheduleRepository)(nil).Update), ctx, schedule)
}
