// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/schedule_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/schedule_usecase.go -destination=internal/domain/mocks/schedule_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduleUseCase is a mock of ScheduleUseCase interface.
type MockScheduleUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleUseCaseMockRecorder
	isgomock struct{}
}

// MockScheduleUseCaseMockRecorder is the mock recorder for MockScheduleUseCase.
type MockScheduleUseCaseMockRecorder struct {
	mock *MockScheduleUseCase
}

// NewMockScheduleUseCase creates a new mock instance.
func NewMockScheduleUseCase(ctrl *gomock.Controller) *MockScheduleUseCase {
	mock := &MockScheduleUseCase{ctrl: ctrl}
	mock.recorder = &MockScheduleUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleUseCase) EXPECT() *MockScheduleUseCaseMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockScheduleUseCase) BulkCreate(ctx context.Context, schedules []*entity.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, schedules)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockScheduleUseCaseMockRecorder) BulkCreate(ctx, schedules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockScheduleUseCase)(nil).BulkCreate), ctx, schedules)
}

// Create mocks base method.
func (m *MockScheduleUseCase) Create(ctx context.Context, schedule *entity.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockScheduleUseCaseMockRecorder) Create(ctx, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScheduleUseCase)(nil).Create), ctx, schedule)
}

// CreateFromTemplate mocks base method.
func (m *MockScheduleUseCase) CreateFromTemplate(ctx context.Context, templateID, classID uuid.UUID, teacherMap map[uuid.UUID]uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFromTemplate", ctx, templateID, classID, teacherMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFromTemplate indicates an expected call of CreateFromTemplate.
func (mr *MockScheduleUseCaseMockRecorder) CreateFromTemplate(ctx, templateID, classID, teacherMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFromTemplate", reflect.TypeOf((*MockScheduleUseCase)(nil).CreateFromTemplate), ctx, templateID, classID, teacherMap)
}

// Delete mocks base method.
func (m *MockScheduleUseCase) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockScheduleUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockScheduleUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockScheduleUseCase) GetByID(ctx context.Context, id uuid.UUID) (*entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockScheduleUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockScheduleUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockScheduleUseCase) List(ctx context.Context, tenantID string, limit, offset int) ([]entity.Schedule, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID, limit, offset)
	ret0, _ := ret[0].([]entity.Schedule)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockScheduleUseCaseMockRecorder) List(ctx, tenantID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockScheduleUseCase)(nil).List), ctx, tenantID, limit, offset)
}

// ListByClass mocks base method.
func (m *MockScheduleUseCase) ListByClass(ctx context.Context, classID uuid.UUID) ([]entity.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClass", ctx, classID)
	ret0, _ := ret[0].([]entity.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClass indicates an expected call of ListByClass.
func (mr *MockScheduleUseCaseMockRecorder) ListByClass(ctx, classID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClass", reflect.TypeOf((*MockScheduleUseCase)(nil).ListByClass), ctx, classID)
}

// Update mocks base method.
func (m *MockScheduleUseCase) Update(ctx context.Context, schedule *entity.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, schedule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockScheduleUseCaseMockRecorder) Update(ctx, schedule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockScheduleUseCase)(nil).Update), ctx, schedule)
}
