// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/school_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/school_repository.go -destination=internal/domain/mocks/school_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSchoolRepository is a mock of SchoolRepository interface.
type MockSchoolRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSchoolRepositoryMockRecorder
	isgomock struct{}
}

// MockSchoolRepositoryMockRecorder is the mock recorder for MockSchoolRepository.
type MockSchoolRepositoryMockRecorder struct {
	mock *MockSchoolRepository
}

// NewMockSchoolRepository creates a new mock instance.
func NewMockSchoolRepository(ctrl *gomock.Controller) *MockSchoolRepository {
	mock := &MockSchoolRepository{ctrl: ctrl}
	mock.recorder = &MockSchoolRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchoolRepository) EXPECT() *MockSchoolRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSchoolRepository) Create(ctx context.Context, school *entity.School) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, school)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSchoolRepositoryMockRecorder) Create(ctx, school any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSchoolRepository)(nil).Create), ctx, school)
}

// Delete mocks base method.
func (m *MockSchoolRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSchoolRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSchoolRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockSchoolRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.School, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.School)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSchoolRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSchoolRepository)(nil).GetByID), ctx, id)
}

// GetByTenantID mocks base method.
func (m *MockSchoolRepository) GetByTenantID(ctx context.Context, tenantID string) (*entity.School, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTenantID", ctx, tenantID)
	ret0, _ := ret[0].(*entity.School)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTenantID indicates an expected call of GetByTenantID.
func (mr *MockSchoolRepositoryMockRecorder) GetByTenantID(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTenantID", reflect.TypeOf((*MockSchoolRepository)(nil).GetByTenantID), ctx, tenantID)
}

// Update mocks base method.
func (m *MockSchoolRepository) Update(ctx context.Context, school *entity.School) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, school)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSchoolRepositoryMockRecorder) Update(ctx, school any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSchoolRepository)(nil).Update), ctx, school)
}
