// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/school_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/school_usecase.go -destination=internal/domain/mocks/school_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSchoolUseCase is a mock of SchoolUseCase interface.
type MockSchoolUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSchoolUseCaseMockRecorder
	isgomock struct{}
}

// MockSchoolUseCaseMockRecorder is the mock recorder for MockSchoolUseCase.
type MockSchoolUseCaseMockRecorder struct {
	mock *MockSchoolUseCase
}

// NewMockSchoolUseCase creates a new mock instance.
func NewMockSchoolUseCase(ctrl *gomock.Controller) *MockSchoolUseCase {
	mock := &MockSchoolUseCase{ctrl: ctrl}
	mock.recorder = &MockSchoolUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchoolUseCase) EXPECT() *MockSchoolUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSchoolUseCase) Create(ctx context.Context, school *entity.School) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, school)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSchoolUseCaseMockRecorder) Create(ctx, school any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSchoolUseCase)(nil).Create), ctx, school)
}

// Delete mocks base method.
func (m *MockSchoolUseCase) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSchoolUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSchoolUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockSchoolUseCase) GetByID(ctx context.Context, id uuid.UUID) (*entity.School, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.School)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSchoolUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSchoolUseCase)(nil).GetByID), ctx, id)
}

// GetByTenantID mocks base method.
func (m *MockSchoolUseCase) GetByTenantID(ctx context.Context, tenantID string) (*entity.School, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTenantID", ctx, tenantID)
	ret0, _ := ret[0].(*entity.School)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTenantID indicates an expected call of GetByTenantID.
func (mr *MockSchoolUseCaseMockRecorder) GetByTenantID(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTenantID", reflect.TypeOf((*MockSchoolUseCase)(nil).GetByTenantID), ctx, tenantID)
}

// Update mocks base method.
func (m *MockSchoolUseCase) Update(ctx context.Context, school *entity.School) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, school)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSchoolUseCaseMockRecorder) Update(ctx, school any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSchoolUseCase)(nil).Update), ctx, school)
}
