// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/semester_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/semester_repository.go -destination=internal/domain/mocks/semester_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSemesterRepository is a mock of SemesterRepository interface.
type MockSemesterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSemesterRepositoryMockRecorder
	isgomock struct{}
}

// MockSemesterRepositoryMockRecorder is the mock recorder for MockSemesterRepository.
type MockSemesterRepositoryMockRecorder struct {
	mock *MockSemesterRepository
}

// NewMockSemesterRepository creates a new mock instance.
func NewMockSemesterRepository(ctrl *gomock.Controller) *MockSemesterRepository {
	mock := &MockSemesterRepository{ctrl: ctrl}
	mock.recorder = &MockSemesterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSemesterRepository) EXPECT() *MockSemesterRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSemesterRepository) Create(ctx context.Context, semester *entity.Semester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, semester)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSemesterRepositoryMockRecorder) Create(ctx, semester any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSemesterRepository)(nil).Create), ctx, semester)
}

// Delete mocks base method.
func (m *MockSemesterRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSemesterRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSemesterRepository)(nil).Delete), ctx, id)
}

// GetActive mocks base method.
func (m *MockSemesterRepository) GetActive(ctx context.Context, tenantID string) (*entity.Semester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActive", ctx, tenantID)
	ret0, _ := ret[0].(*entity.Semester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActive indicates an expected call of GetActive.
func (mr *MockSemesterRepositoryMockRecorder) GetActive(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActive", reflect.TypeOf((*MockSemesterRepository)(nil).GetActive), ctx, tenantID)
}

// GetByID mocks base method.
func (m *MockSemesterRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Semester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Semester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSemesterRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSemesterRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockSemesterRepository) List(ctx context.Context, tenantID string) ([]entity.Semester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID)
	ret0, _ := ret[0].([]entity.Semester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSemesterRepositoryMockRecorder) List(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSemesterRepository)(nil).List), ctx, tenantID)
}

// ListByAcademicYear mocks base method.
func (m *MockSemesterRepository) ListByAcademicYear(ctx context.Context, academicYearID uuid.UUID) ([]entity.Semester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAcademicYear", ctx, academicYearID)
	ret0, _ := ret[0].([]entity.Semester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAcademicYear indicates an expected call of ListByAcademicYear.
func (mr *MockSemesterRepositoryMockRecorder) ListByAcademicYear(ctx, academicYearID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAcademicYear", reflect.TypeOf((*MockSemesterRepository)(nil).ListByAcademicYear), ctx, academicYearID)
}

// Update mocks base method.
func (m *MockSemesterRepository) Update(ctx context.Context, semester *entity.Semester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, semester)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSemesterRepositoryMockRecorder) Update(ctx, semester any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSemesterRepository)(nil).Update), ctx, semester)
}
