// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/student_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/student_usecase.go -destination=internal/domain/mocks/student_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockStudentUseCase is a mock of StudentUseCase interface.
type MockStudentUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockStudentUseCaseMockRecorder
	isgomock struct{}
}

// MockStudentUseCaseMockRecorder is the mock recorder for MockStudentUseCase.
type MockStudentUseCaseMockRecorder struct {
	mock *MockStudentUseCase
}

// NewMockStudentUseCase creates a new mock instance.
func NewMockStudentUseCase(ctrl *gomock.Controller) *MockStudentUseCase {
	mock := &MockStudentUseCase{ctrl: ctrl}
	mock.recorder = &MockStudentUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentUseCase) EXPECT() *MockStudentUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStudentUseCase) Create(ctx context.Context, student *entity.Student) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, student)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStudentUseCaseMockRecorder) Create(ctx, student any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStudentUseCase)(nil).Create), ctx, student)
}

// Delete mocks base method.
func (m *MockStudentUseCase) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStudentUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStudentUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockStudentUseCase) GetByID(ctx context.Context, id uuid.UUID) (*entity.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockStudentUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockStudentUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockStudentUseCase) List(ctx context.Context, tenantID string, limit, offset int) ([]entity.Student, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID, limit, offset)
	ret0, _ := ret[0].([]entity.Student)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockStudentUseCaseMockRecorder) List(ctx, tenantID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStudentUseCase)(nil).List), ctx, tenantID, limit, offset)
}

// Update mocks base method.
func (m *MockStudentUseCase) Update(ctx context.Context, student *entity.Student) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, student)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockStudentUseCaseMockRecorder) Update(ctx, student any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockStudentUseCase)(nil).Update), ctx, student)
}
