// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/subject_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/subject_repository.go -destination=internal/domain/mocks/subject_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSubjectRepository is a mock of SubjectRepository interface.
type MockSubjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubjectRepositoryMockRecorder
	isgomock struct{}
}

// MockSubjectRepositoryMockRecorder is the mock recorder for MockSubjectRepository.
type MockSubjectRepositoryMockRecorder struct {
	mock *MockSubjectRepository
}

// NewMockSubjectRepository creates a new mock instance.
func NewMockSubjectRepository(ctrl *gomock.Controller) *MockSubjectRepository {
	mock := &MockSubjectRepository{ctrl: ctrl}
	mock.recorder = &MockSubjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubjectRepository) EXPECT() *MockSubjectRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSubjectRepository) Create(ctx context.Context, subject *entity.Subject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, subject)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSubjectRepositoryMockRecorder) Create(ctx, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubjectRepository)(nil).Create), ctx, subject)
}

// Delete mocks base method.
func (m *MockSubjectRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSubjectRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubjectRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockSubjectRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSubjectRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSubjectRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockSubjectRepository) List(ctx context.Context, tenantID string, limit, offset int) ([]entity.Subject, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID, limit, offset)
	ret0, _ := ret[0].([]entity.Subject)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSubjectRepositoryMockRecorder) List(ctx, tenantID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSubjectRepository)(nil).List), ctx, tenantID, limit, offset)
}

// Update mocks base method.
func (m *MockSubjectRepository) Update(ctx context.Context, subject *entity.Subject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, subject)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSubjectRepositoryMockRecorder) Update(ctx, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubjectRepository)(nil).Update), ctx, subject)
}
