// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/teacher_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/teacher_repository.go -destination=internal/domain/mocks/teacher_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTeacherRepository is a mock of TeacherRepository interface.
type MockTeacherRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeacherRepositoryMockRecorder
	isgomock struct{}
}

// MockTeacherRepositoryMockRecorder is the mock recorder for MockTeacherRepository.
type MockTeacherRepositoryMockRecorder struct {
	mock *MockTeacherRepository
}

// NewMockTeacherRepository creates a new mock instance.
func NewMockTeacherRepository(ctrl *gomock.Controller) *MockTeacherRepository {
	mock := &MockTeacherRepository{ctrl: ctrl}
	mock.recorder = &MockTeacherRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeacherRepository) EXPECT() *MockTeacherRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTeacherRepository) Create(ctx context.Context, teacher *entity.Teacher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, teacher)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTeacherRepositoryMockRecorder) Create(ctx, teacher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeacherRepository)(nil).Create), ctx, teacher)
}

// Delete mocks base method.
func (m *MockTeacherRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTeacherRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeacherRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockTeacherRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Teacher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Teacher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTeacherRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTeacherRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockTeacherRepository) List(ctx context.Context, tenantID string, limit, offset int) ([]entity.Teacher, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID, limit, offset)
	ret0, _ := ret[0].([]entity.Teacher)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTeacherRepositoryMockRecorder) List(ctx, tenantID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTeacherRepository)(nil).List), ctx, tenantID, limit, offset)
}

// Update mocks base method.
func (m *MockTeacherRepository) Update(ctx context.Context, teacher *entity.Teacher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, teacher)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTeacherRepositoryMockRecorder) Update(ctx, teacher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTeacherRepository)(nil).Update), ctx, teacher)
}
