// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/teacher_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/teacher_usecase.go -destination=internal/domain/mocks/teacher_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/academic-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTeacherUseCase is a mock of TeacherUseCase interface.
type MockTeacherUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTeacherUseCaseMockRecorder
	isgomock struct{}
}

// MockTeacherUseCaseMockRecorder is the mock recorder for MockTeacherUseCase.
type MockTeacherUseCaseMockRecorder struct {
	mock *MockTeacherUseCase
}

// NewMockTeacherUseCase creates a new mock instance.
func NewMockTeacherUseCase(ctrl *gomock.Controller) *MockTeacherUseCase {
	mock := &MockTeacherUseCase{ctrl: ctrl}
	mock.recorder = &MockTeacherUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeacherUseCase) EXPECT() *MockTeacherUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTeacherUseCase) Create(ctx context.Context, teacher *entity.Teacher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, teacher)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTeacherUseCaseMockRecorder) Create(ctx, teacher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeacherUseCase)(nil).Create), ctx, teacher)
}

// Delete mocks base method.
func (m *MockTeacherUseCase) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTeacherUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeacherUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockTeacherUseCase) GetByID(ctx context.Context, id uuid.UUID) (*entity.Teacher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Teacher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTeacherUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTeacherUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockTeacherUseCase) List(ctx context.Context, tenantID string, limit, offset int) ([]entity.Teacher, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID, limit, offset)
	ret0, _ := ret[0].([]entity.Teacher)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTeacherUseCaseMockRecorder) List(ctx, tenantID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTeacherUseCase)(nil).List), ctx, tenantID, limit, offset)
}

// Update mocks base method.
func (m *MockTeacherUseCase) Update(ctx context.Context, teacher *entity.Teacher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, teacher)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTeacherUseCaseMockRecorder) Update(ctx, teacher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTeacherUseCase)(nil).Update), ctx, teacher)
}
