package usecase

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/jjaenal/sisfo-akademik-backend/services/assessment-service/internal/domain/entity"
	"github.com/johnfercher/maroto/pkg/color"
	"github.com/johnfercher/maroto/pkg/consts"
	"github.com/johnfercher/maroto/pkg/pdf"
	"github.com/johnfercher/maroto/pkg/props"
)

func (u *reportCardUseCase) GetPDF(ctx context.Context, id uuid.UUID) ([]byte, error) {
	report, err := u.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if report == nil {
		return nil, fmt.Errorf("report card not found")
	}

	return u.generatePDF(report)
}

func (u *reportCardUseCase) generatePDF(report *entity.ReportCard) ([]byte, error) {
	m := pdf.NewMaroto(consts.Portrait, consts.A4)
	m.SetPageMargins(20, 10, 20)

	u.buildHeader(m, report)
	u.buildStudentInfo(m, report)
	u.buildGradesTable(m, report)
	u.buildFooter(m, report)

	buffer, err := m.Output()
	if err != nil {
		return nil, err
	}
	return buffer.Bytes(), nil
}

func (u *reportCardUseCase) buildHeader(m pdf.Maroto, report *entity.ReportCard) {
	m.RegisterHeader(func() {
		m.Row(10, func() {
			m.Col(12, func() {
				m.Text("ACADEMIC REPORT CARD", props.Text{
					Top:   3,
					Style: consts.Bold,
					Align: consts.Center,
					Size:  16,
				})
			})
		})
	})
}

func (u *reportCardUseCase) buildStudentInfo(m pdf.Maroto, report *entity.ReportCard) {
	m.Row(10, func() {
		m.Col(12, func() {
			m.Text(fmt.Sprintf("Report ID: %s", report.ID.String()), props.Text{
				Size: 8,
				Top:  2,
				Align: consts.Right,
			})
		})
	})

	m.Row(10, func() {
		m.Col(6, func() {
			m.Text(fmt.Sprintf("Student ID: %s", report.StudentID.String()), props.Text{
				Size: 10,
				Top:  2,
			})
		})
		m.Col(6, func() {
			m.Text(fmt.Sprintf("Class ID: %s", report.ClassID.String()), props.Text{
				Size: 10,
				Top:  2,
				Align: consts.Right,
			})
		})
	})

	m.Row(10, func() {
		m.Col(6, func() {
			m.Text(fmt.Sprintf("Semester ID: %s", report.SemesterID.String()), props.Text{
				Size: 10,
				Top:  2,
			})
		})
		m.Col(6, func() {
			dateStr := ""
			if report.GeneratedAt != nil {
				dateStr = report.GeneratedAt.Format("2006-01-02")
			}
			m.Text(fmt.Sprintf("Generated At: %s", dateStr), props.Text{
				Size: 10,
				Top:  2,
				Align: consts.Right,
			})
		})
	})
	
	m.Line(1.0)
}

func (u *reportCardUseCase) buildGradesTable(m pdf.Maroto, report *entity.ReportCard) {
	m.Row(10, func() {
		m.Col(12, func() {
			m.Text("Academic Performance", props.Text{
				Top:   5,
				Style: consts.Bold,
				Size:  12,
			})
		})
	})

	header := []string{"Subject", "Credits", "Score", "Grade", "Comments"}
	m.TableList(header, u.getContents(report.Details), props.TableList{
		HeaderProp: props.TableListContent{
			Size:      10,
			GridSizes: []uint{4, 2, 2, 2, 2},
		},
		ContentProp: props.TableListContent{
			Size:      10,
			GridSizes: []uint{4, 2, 2, 2, 2},
		},
		Align: consts.Center,
		AlternatedBackground: &color.Color{
			Red:   240,
			Green: 240,
			Blue:  240,
		},
		HeaderContentSpace: 4,
		Line:               true,
	})
	
	m.Row(10, func() {
		m.Col(12, func() {
			m.Text(fmt.Sprintf("GPA: %.2f   Total Credits: %d", report.GPA, report.TotalCredits), props.Text{
				Top:   5,
				Style: consts.Bold,
				Align: consts.Right,
				Size:  12,
			})
		})
	})
}

func (u *reportCardUseCase) getContents(details []entity.ReportCardDetail) [][]string {
	var contents [][]string
	for _, d := range details {
		contents = append(contents, []string{
			d.SubjectName,
			fmt.Sprintf("%d", d.Credit),
			fmt.Sprintf("%.2f", d.FinalScore),
			d.GradeLetter,
			d.Comments,
		})
	}
	return contents
}

func (u *reportCardUseCase) buildFooter(m pdf.Maroto, report *entity.ReportCard) {
	m.RegisterFooter(func() {
		m.Row(10, func() {
			m.Col(12, func() {
				m.Text("Generated by SISFO Akademik", props.Text{
					Top:   5,
					Style: consts.Italic,
					Align: consts.Center,
					Size:  8,
				})
			})
		})
	})
}
