// Code generated by MockGen. DO NOT EDIT.
// Source: services/finance-service/internal/usecase/billing_config_usecase.go
//
// Generated by this command:
//
//	mockgen -source=services/finance-service/internal/usecase/billing_config_usecase.go -destination=services/finance-service/internal/usecase/mocks/billing_config_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/finance-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockBillingConfigUseCase is a mock of BillingConfigUseCase interface.
type MockBillingConfigUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockBillingConfigUseCaseMockRecorder
	isgomock struct{}
}

// MockBillingConfigUseCaseMockRecorder is the mock recorder for MockBillingConfigUseCase.
type MockBillingConfigUseCaseMockRecorder struct {
	mock *MockBillingConfigUseCase
}

// NewMockBillingConfigUseCase creates a new mock instance.
func NewMockBillingConfigUseCase(ctrl *gomock.Controller) *MockBillingConfigUseCase {
	mock := &MockBillingConfigUseCase{ctrl: ctrl}
	mock.recorder = &MockBillingConfigUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingConfigUseCase) EXPECT() *MockBillingConfigUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBillingConfigUseCase) Create(ctx context.Context, config *entity.BillingConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBillingConfigUseCaseMockRecorder) Create(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBillingConfigUseCase)(nil).Create), ctx, config)
}

// Delete mocks base method.
func (m *MockBillingConfigUseCase) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBillingConfigUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBillingConfigUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockBillingConfigUseCase) GetByID(ctx context.Context, id uuid.UUID) (*entity.BillingConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.BillingConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBillingConfigUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBillingConfigUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockBillingConfigUseCase) List(ctx context.Context, tenantID uuid.UUID) ([]*entity.BillingConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID)
	ret0, _ := ret[0].([]*entity.BillingConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBillingConfigUseCaseMockRecorder) List(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBillingConfigUseCase)(nil).List), ctx, tenantID)
}

// Update mocks base method.
func (m *MockBillingConfigUseCase) Update(ctx context.Context, config *entity.BillingConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBillingConfigUseCaseMockRecorder) Update(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBillingConfigUseCase)(nil).Update), ctx, config)
}
