// Code generated by MockGen. DO NOT EDIT.
// Source: services/finance-service/internal/usecase/invoice_usecase.go
//
// Generated by this command:
//
//	mockgen -source=services/finance-service/internal/usecase/invoice_usecase.go -destination=services/finance-service/internal/usecase/mocks/invoice_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/finance-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockInvoiceUseCase is a mock of InvoiceUseCase interface.
type MockInvoiceUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceUseCaseMockRecorder
	isgomock struct{}
}

// MockInvoiceUseCaseMockRecorder is the mock recorder for MockInvoiceUseCase.
type MockInvoiceUseCaseMockRecorder struct {
	mock *MockInvoiceUseCase
}

// NewMockInvoiceUseCase creates a new mock instance.
func NewMockInvoiceUseCase(ctrl *gomock.Controller) *MockInvoiceUseCase {
	mock := &MockInvoiceUseCase{ctrl: ctrl}
	mock.recorder = &MockInvoiceUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceUseCase) EXPECT() *MockInvoiceUseCaseMockRecorder {
	return m.recorder
}

// CheckOverdueInvoices mocks base method.
func (m *MockInvoiceUseCase) CheckOverdueInvoices(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOverdueInvoices", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckOverdueInvoices indicates an expected call of CheckOverdueInvoices.
func (mr *MockInvoiceUseCaseMockRecorder) CheckOverdueInvoices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOverdueInvoices", reflect.TypeOf((*MockInvoiceUseCase)(nil).CheckOverdueInvoices), ctx)
}

// Generate mocks base method.
func (m *MockInvoiceUseCase) Generate(ctx context.Context, tenantID, studentID, billingConfigID uuid.UUID) (*entity.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, tenantID, studentID, billingConfigID)
	ret0, _ := ret[0].(*entity.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockInvoiceUseCaseMockRecorder) Generate(ctx, tenantID, studentID, billingConfigID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockInvoiceUseCase)(nil).Generate), ctx, tenantID, studentID, billingConfigID)
}

// GenerateAllMonthlyInvoices mocks base method.
func (m *MockInvoiceUseCase) GenerateAllMonthlyInvoices(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAllMonthlyInvoices", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateAllMonthlyInvoices indicates an expected call of GenerateAllMonthlyInvoices.
func (mr *MockInvoiceUseCaseMockRecorder) GenerateAllMonthlyInvoices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAllMonthlyInvoices", reflect.TypeOf((*MockInvoiceUseCase)(nil).GenerateAllMonthlyInvoices), ctx)
}

// GetByID mocks base method.
func (m *MockInvoiceUseCase) GetByID(ctx context.Context, id uuid.UUID) (*entity.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockInvoiceUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockInvoiceUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockInvoiceUseCase) List(ctx context.Context, tenantID, studentID uuid.UUID, status entity.InvoiceStatus) ([]*entity.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID, studentID, status)
	ret0, _ := ret[0].([]*entity.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInvoiceUseCaseMockRecorder) List(ctx, tenantID, studentID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInvoiceUseCase)(nil).List), ctx, tenantID, studentID, status)
}
