// Code generated by MockGen. DO NOT EDIT.
// Source: services/finance-service/internal/usecase/report_usecase.go
//
// Generated by this command:
//
//	mockgen -source=services/finance-service/internal/usecase/report_usecase.go -destination=services/finance-service/internal/usecase/mocks/report_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/finance-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockReportUseCase is a mock of ReportUseCase interface.
type MockReportUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockReportUseCaseMockRecorder
	isgomock struct{}
}

// MockReportUseCaseMockRecorder is the mock recorder for MockReportUseCase.
type MockReportUseCaseMockRecorder struct {
	mock *MockReportUseCase
}

// NewMockReportUseCase creates a new mock instance.
func NewMockReportUseCase(ctrl *gomock.Controller) *MockReportUseCase {
	mock := &MockReportUseCase{ctrl: ctrl}
	mock.recorder = &MockReportUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportUseCase) EXPECT() *MockReportUseCaseMockRecorder {
	return m.recorder
}

// GetDailyRevenue mocks base method.
func (m *MockReportUseCase) GetDailyRevenue(ctx context.Context, tenantID uuid.UUID, startDate, endDate time.Time) ([]*entity.DailyRevenue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyRevenue", ctx, tenantID, startDate, endDate)
	ret0, _ := ret[0].([]*entity.DailyRevenue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyRevenue indicates an expected call of GetDailyRevenue.
func (mr *MockReportUseCaseMockRecorder) GetDailyRevenue(ctx, tenantID, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyRevenue", reflect.TypeOf((*MockReportUseCase)(nil).GetDailyRevenue), ctx, tenantID, startDate, endDate)
}

// GetMonthlyRevenue mocks base method.
func (m *MockReportUseCase) GetMonthlyRevenue(ctx context.Context, tenantID uuid.UUID, year int) ([]*entity.MonthlyRevenue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonthlyRevenue", ctx, tenantID, year)
	ret0, _ := ret[0].([]*entity.MonthlyRevenue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonthlyRevenue indicates an expected call of GetMonthlyRevenue.
func (mr *MockReportUseCaseMockRecorder) GetMonthlyRevenue(ctx, tenantID, year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonthlyRevenue", reflect.TypeOf((*MockReportUseCase)(nil).GetMonthlyRevenue), ctx, tenantID, year)
}

// GetOutstandingInvoices mocks base method.
func (m *MockReportUseCase) GetOutstandingInvoices(ctx context.Context, tenantID uuid.UUID) ([]*entity.OutstandingReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutstandingInvoices", ctx, tenantID)
	ret0, _ := ret[0].([]*entity.OutstandingReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutstandingInvoices indicates an expected call of GetOutstandingInvoices.
func (mr *MockReportUseCaseMockRecorder) GetOutstandingInvoices(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutstandingInvoices", reflect.TypeOf((*MockReportUseCase)(nil).GetOutstandingInvoices), ctx, tenantID)
}

// GetStudentHistory mocks base method.
func (m *MockReportUseCase) GetStudentHistory(ctx context.Context, tenantID, studentID uuid.UUID) (*entity.StudentHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentHistory", ctx, tenantID, studentID)
	ret0, _ := ret[0].(*entity.StudentHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentHistory indicates an expected call of GetStudentHistory.
func (mr *MockReportUseCaseMockRecorder) GetStudentHistory(ctx, tenantID, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentHistory", reflect.TypeOf((*MockReportUseCase)(nil).GetStudentHistory), ctx, tenantID, studentID)
}
