// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/grading_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/grading_usecase.go -destination=internal/domain/mocks/grading_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/assessment-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockGradingUseCase is a mock of GradingUseCase interface.
type MockGradingUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGradingUseCaseMockRecorder
	isgomock struct{}
}

// MockGradingUseCaseMockRecorder is the mock recorder for MockGradingUseCase.
type MockGradingUseCaseMockRecorder struct {
	mock *MockGradingUseCase
}

// NewMockGradingUseCase creates a new mock instance.
func NewMockGradingUseCase(ctrl *gomock.Controller) *MockGradingUseCase {
	mock := &MockGradingUseCase{ctrl: ctrl}
	mock.recorder = &MockGradingUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGradingUseCase) EXPECT() *MockGradingUseCaseMockRecorder {
	return m.recorder
}

// ApproveGrade mocks base method.
func (m *MockGradingUseCase) ApproveGrade(ctx context.Context, gradeID, approvedBy uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveGrade", ctx, gradeID, approvedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveGrade indicates an expected call of ApproveGrade.
func (mr *MockGradingUseCaseMockRecorder) ApproveGrade(ctx, gradeID, approvedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveGrade", reflect.TypeOf((*MockGradingUseCase)(nil).ApproveGrade), ctx, gradeID, approvedBy)
}

// CalculateFinalScore mocks base method.
func (m *MockGradingUseCase) CalculateFinalScore(ctx context.Context, studentID, classID, subjectID, semesterID uuid.UUID) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateFinalScore", ctx, studentID, classID, subjectID, semesterID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateFinalScore indicates an expected call of CalculateFinalScore.
func (mr *MockGradingUseCaseMockRecorder) CalculateFinalScore(ctx, studentID, classID, subjectID, semesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateFinalScore", reflect.TypeOf((*MockGradingUseCase)(nil).CalculateFinalScore), ctx, studentID, classID, subjectID, semesterID)
}

// CreateAssessment mocks base method.
func (m *MockGradingUseCase) CreateAssessment(ctx context.Context, assessment *entity.Assessment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAssessment", ctx, assessment)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAssessment indicates an expected call of CreateAssessment.
func (mr *MockGradingUseCaseMockRecorder) CreateAssessment(ctx, assessment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAssessment", reflect.TypeOf((*MockGradingUseCase)(nil).CreateAssessment), ctx, assessment)
}

// GetStudentGrades mocks base method.
func (m *MockGradingUseCase) GetStudentGrades(ctx context.Context, studentID, classID, semesterID uuid.UUID) ([]*entity.Grade, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentGrades", ctx, studentID, classID, semesterID)
	ret0, _ := ret[0].([]*entity.Grade)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentGrades indicates an expected call of GetStudentGrades.
func (mr *MockGradingUseCaseMockRecorder) GetStudentGrades(ctx, studentID, classID, semesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentGrades", reflect.TypeOf((*MockGradingUseCase)(nil).GetStudentGrades), ctx, studentID, classID, semesterID)
}

// InputGrade mocks base method.
func (m *MockGradingUseCase) InputGrade(ctx context.Context, grade *entity.Grade) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputGrade", ctx, grade)
	ret0, _ := ret[0].(error)
	return ret0
}

// InputGrade indicates an expected call of InputGrade.
func (mr *MockGradingUseCaseMockRecorder) InputGrade(ctx, grade any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputGrade", reflect.TypeOf((*MockGradingUseCase)(nil).InputGrade), ctx, grade)
}
