// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/grade_category_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/grade_category_repository.go -destination=internal/domain/mocks/grade_category_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/assessment-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockGradeCategoryRepository is a mock of GradeCategoryRepository interface.
type MockGradeCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGradeCategoryRepositoryMockRecorder
	isgomock struct{}
}

// MockGradeCategoryRepositoryMockRecorder is the mock recorder for MockGradeCategoryRepository.
type MockGradeCategoryRepositoryMockRecorder struct {
	mock *MockGradeCategoryRepository
}

// NewMockGradeCategoryRepository creates a new mock instance.
func NewMockGradeCategoryRepository(ctrl *gomock.Controller) *MockGradeCategoryRepository {
	mock := &MockGradeCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockGradeCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGradeCategoryRepository) EXPECT() *MockGradeCategoryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGradeCategoryRepository) Create(ctx context.Context, category *entity.GradeCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGradeCategoryRepositoryMockRecorder) Create(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGradeCategoryRepository)(nil).Create), ctx, category)
}

// Delete mocks base method.
func (m *MockGradeCategoryRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGradeCategoryRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGradeCategoryRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockGradeCategoryRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.GradeCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.GradeCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGradeCategoryRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGradeCategoryRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockGradeCategoryRepository) List(ctx context.Context) ([]*entity.GradeCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.GradeCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGradeCategoryRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGradeCategoryRepository)(nil).List), ctx)
}

// GetByTenantID mocks base method.
func (m *MockGradeCategoryRepository) GetByTenantID(ctx context.Context, tenantID string) ([]*entity.GradeCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTenantID", ctx, tenantID)
	ret0, _ := ret[0].([]*entity.GradeCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTenantID indicates an expected call of GetByTenantID.
func (mr *MockGradeCategoryRepositoryMockRecorder) GetByTenantID(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTenantID", reflect.TypeOf((*MockGradeCategoryRepository)(nil).GetByTenantID), ctx, tenantID)
}

// Update mocks base method.
func (m *MockGradeCategoryRepository) Update(ctx context.Context, category *entity.GradeCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGradeCategoryRepositoryMockRecorder) Update(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGradeCategoryRepository)(nil).Update), ctx, category)
}
