// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/grade_category_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/grade_category_usecase.go -destination=internal/domain/mocks/grade_category_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/assessment-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockGradeCategoryUseCase is a mock of GradeCategoryUseCase interface.
type MockGradeCategoryUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGradeCategoryUseCaseMockRecorder
	isgomock struct{}
}

// MockGradeCategoryUseCaseMockRecorder is the mock recorder for MockGradeCategoryUseCase.
type MockGradeCategoryUseCaseMockRecorder struct {
	mock *MockGradeCategoryUseCase
}

// NewMockGradeCategoryUseCase creates a new mock instance.
func NewMockGradeCategoryUseCase(ctrl *gomock.Controller) *MockGradeCategoryUseCase {
	mock := &MockGradeCategoryUseCase{ctrl: ctrl}
	mock.recorder = &MockGradeCategoryUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGradeCategoryUseCase) EXPECT() *MockGradeCategoryUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGradeCategoryUseCase) Create(ctx context.Context, category *entity.GradeCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGradeCategoryUseCaseMockRecorder) Create(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGradeCategoryUseCase)(nil).Create), ctx, category)
}

// Delete mocks base method.
func (m *MockGradeCategoryUseCase) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGradeCategoryUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGradeCategoryUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockGradeCategoryUseCase) GetByID(ctx context.Context, id uuid.UUID) (*entity.GradeCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.GradeCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGradeCategoryUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGradeCategoryUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockGradeCategoryUseCase) List(ctx context.Context) ([]*entity.GradeCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.GradeCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGradeCategoryUseCaseMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGradeCategoryUseCase)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockGradeCategoryUseCase) Update(ctx context.Context, category *entity.GradeCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockGradeCategoryUseCaseMockRecorder) Update(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGradeCategoryUseCase)(nil).Update), ctx, category)
}
