// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usecase/report_card_usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usecase/report_card_usecase.go -destination=internal/domain/mocks/report_card_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/assessment-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockReportCardUseCase is a mock of ReportCardUseCase interface.
type MockReportCardUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockReportCardUseCaseMockRecorder
	isgomock struct{}
}

// MockReportCardUseCaseMockRecorder is the mock recorder for MockReportCardUseCase.
type MockReportCardUseCaseMockRecorder struct {
	mock *MockReportCardUseCase
}

// NewMockReportCardUseCase creates a new mock instance.
func NewMockReportCardUseCase(ctrl *gomock.Controller) *MockReportCardUseCase {
	mock := &MockReportCardUseCase{ctrl: ctrl}
	mock.recorder = &MockReportCardUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportCardUseCase) EXPECT() *MockReportCardUseCaseMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockReportCardUseCase) Generate(ctx context.Context, tenantID, studentID, classID, semesterID uuid.UUID) (*entity.ReportCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, tenantID, studentID, classID, semesterID)
	ret0, _ := ret[0].(*entity.ReportCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockReportCardUseCaseMockRecorder) Generate(ctx, tenantID, studentID, classID, semesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockReportCardUseCase)(nil).Generate), ctx, tenantID, studentID, classID, semesterID)
}

// GetByID mocks base method.
func (m *MockReportCardUseCase) GetByID(ctx context.Context, id uuid.UUID) (*entity.ReportCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.ReportCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReportCardUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReportCardUseCase)(nil).GetByID), ctx, id)
}

// GetByStudent mocks base method.
func (m *MockReportCardUseCase) GetByStudent(ctx context.Context, studentID, semesterID uuid.UUID) (*entity.ReportCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStudent", ctx, studentID, semesterID)
	ret0, _ := ret[0].(*entity.ReportCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStudent indicates an expected call of GetByStudent.
func (mr *MockReportCardUseCaseMockRecorder) GetByStudent(ctx, studentID, semesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStudent", reflect.TypeOf((*MockReportCardUseCase)(nil).GetByStudent), ctx, studentID, semesterID)
}

// GetPDF mocks base method.
func (m *MockReportCardUseCase) GetPDF(ctx context.Context, id uuid.UUID) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPDF", ctx, id)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPDF indicates an expected call of GetPDF.
func (mr *MockReportCardUseCaseMockRecorder) GetPDF(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPDF", reflect.TypeOf((*MockReportCardUseCase)(nil).GetPDF), ctx, id)
}

// Publish mocks base method.
func (m *MockReportCardUseCase) Publish(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockReportCardUseCaseMockRecorder) Publish(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockReportCardUseCase)(nil).Publish), ctx, id)
}
