// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/report_card_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/report_card_repository.go -destination=internal/domain/mocks/report_card_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/assessment-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockReportCardRepository is a mock of ReportCardRepository interface.
type MockReportCardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReportCardRepositoryMockRecorder
	isgomock struct{}
}

// MockReportCardRepositoryMockRecorder is the mock recorder for MockReportCardRepository.
type MockReportCardRepositoryMockRecorder struct {
	mock *MockReportCardRepository
}

// NewMockReportCardRepository creates a new mock instance.
func NewMockReportCardRepository(ctrl *gomock.Controller) *MockReportCardRepository {
	mock := &MockReportCardRepository{ctrl: ctrl}
	mock.recorder = &MockReportCardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportCardRepository) EXPECT() *MockReportCardRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReportCardRepository) Create(ctx context.Context, rc *entity.ReportCard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReportCardRepositoryMockRecorder) Create(ctx, rc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReportCardRepository)(nil).Create), ctx, rc)
}

// GetByID mocks base method.
func (m *MockReportCardRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.ReportCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.ReportCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReportCardRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReportCardRepository)(nil).GetByID), ctx, id)
}

// GetByStudentAndSemester mocks base method.
func (m *MockReportCardRepository) GetByStudentAndSemester(ctx context.Context, studentID, semesterID uuid.UUID) (*entity.ReportCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByStudentAndSemester", ctx, studentID, semesterID)
	ret0, _ := ret[0].(*entity.ReportCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByStudentAndSemester indicates an expected call of GetByStudentAndSemester.
func (mr *MockReportCardRepositoryMockRecorder) GetByStudentAndSemester(ctx, studentID, semesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByStudentAndSemester", reflect.TypeOf((*MockReportCardRepository)(nil).GetByStudentAndSemester), ctx, studentID, semesterID)
}

// List mocks base method.
func (m *MockReportCardRepository) List(ctx context.Context, classID, semesterID uuid.UUID) ([]*entity.ReportCard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, classID, semesterID)
	ret0, _ := ret[0].([]*entity.ReportCard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockReportCardRepositoryMockRecorder) List(ctx, classID, semesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockReportCardRepository)(nil).List), ctx, classID, semesterID)
}

// Update mocks base method.
func (m *MockReportCardRepository) Update(ctx context.Context, rc *entity.ReportCard) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, rc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockReportCardRepositoryMockRecorder) Update(ctx, rc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockReportCardRepository)(nil).Update), ctx, rc)
}
