// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/notification_template_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/notification_template_repository.go -destination=internal/domain/mocks/notification_template_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/notification-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationTemplateRepository is a mock of NotificationTemplateRepository interface.
type MockNotificationTemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationTemplateRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationTemplateRepositoryMockRecorder is the mock recorder for MockNotificationTemplateRepository.
type MockNotificationTemplateRepositoryMockRecorder struct {
	mock *MockNotificationTemplateRepository
}

// NewMockNotificationTemplateRepository creates a new mock instance.
func NewMockNotificationTemplateRepository(ctrl *gomock.Controller) *MockNotificationTemplateRepository {
	mock := &MockNotificationTemplateRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationTemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationTemplateRepository) EXPECT() *MockNotificationTemplateRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNotificationTemplateRepository) Create(ctx context.Context, template *entity.NotificationTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationTemplateRepositoryMockRecorder) Create(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationTemplateRepository)(nil).Create), ctx, template)
}

// Delete mocks base method.
func (m *MockNotificationTemplateRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNotificationTemplateRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotificationTemplateRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockNotificationTemplateRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockNotificationTemplateRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockNotificationTemplateRepository)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockNotificationTemplateRepository) GetByName(ctx context.Context, name string) (*entity.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*entity.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockNotificationTemplateRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockNotificationTemplateRepository)(nil).GetByName), ctx, name)
}

// List mocks base method.
func (m *MockNotificationTemplateRepository) List(ctx context.Context) ([]*entity.NotificationTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*entity.NotificationTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNotificationTemplateRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNotificationTemplateRepository)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockNotificationTemplateRepository) Update(ctx context.Context, template *entity.NotificationTemplate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, template)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNotificationTemplateRepositoryMockRecorder) Update(ctx, template any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNotificationTemplateRepository)(nil).Update), ctx, template)
}
