// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/whatsapp_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/service/whatsapp_service.go -destination=internal/domain/mocks/whatsapp_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWhatsAppService is a mock of WhatsAppService interface.
type MockWhatsAppService struct {
	ctrl     *gomock.Controller
	recorder *MockWhatsAppServiceMockRecorder
	isgomock struct{}
}

// MockWhatsAppServiceMockRecorder is the mock recorder for MockWhatsAppService.
type MockWhatsAppServiceMockRecorder struct {
	mock *MockWhatsAppService
}

// NewMockWhatsAppService creates a new mock instance.
func NewMockWhatsAppService(ctrl *gomock.Controller) *MockWhatsAppService {
	mock := &MockWhatsAppService{ctrl: ctrl}
	mock.recorder = &MockWhatsAppServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWhatsAppService) EXPECT() *MockWhatsAppServiceMockRecorder {
	return m.recorder
}

// SendWhatsApp mocks base method.
func (m *MockWhatsAppService) SendWhatsApp(to, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWhatsApp", to, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWhatsApp indicates an expected call of SendWhatsApp.
func (mr *MockWhatsAppServiceMockRecorder) SendWhatsApp(to, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWhatsApp", reflect.TypeOf((*MockWhatsAppService)(nil).SendWhatsApp), to, message)
}
