// Code generated by MockGen. DO NOT EDIT.
// Source: services/finance-service/internal/domain/repository/billing_config_repository.go
//
// Generated by this command:
//
//	mockgen -source=services/finance-service/internal/domain/repository/billing_config_repository.go -destination=services/finance-service/internal/domain/mocks/billing_config_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/finance-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockBillingConfigRepository is a mock of BillingConfigRepository interface.
type MockBillingConfigRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBillingConfigRepositoryMockRecorder
	isgomock struct{}
}

// MockBillingConfigRepositoryMockRecorder is the mock recorder for MockBillingConfigRepository.
type MockBillingConfigRepositoryMockRecorder struct {
	mock *MockBillingConfigRepository
}

// NewMockBillingConfigRepository creates a new mock instance.
func NewMockBillingConfigRepository(ctrl *gomock.Controller) *MockBillingConfigRepository {
	mock := &MockBillingConfigRepository{ctrl: ctrl}
	mock.recorder = &MockBillingConfigRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingConfigRepository) EXPECT() *MockBillingConfigRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBillingConfigRepository) Create(ctx context.Context, config *entity.BillingConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBillingConfigRepositoryMockRecorder) Create(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBillingConfigRepository)(nil).Create), ctx, config)
}

// Delete mocks base method.
func (m *MockBillingConfigRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBillingConfigRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBillingConfigRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockBillingConfigRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.BillingConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.BillingConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBillingConfigRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBillingConfigRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockBillingConfigRepository) List(ctx context.Context, tenantID uuid.UUID) ([]*entity.BillingConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID)
	ret0, _ := ret[0].([]*entity.BillingConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBillingConfigRepositoryMockRecorder) List(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBillingConfigRepository)(nil).List), ctx, tenantID)
}

// ListAllActiveMonthly mocks base method.
func (m *MockBillingConfigRepository) ListAllActiveMonthly(ctx context.Context) ([]*entity.BillingConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllActiveMonthly", ctx)
	ret0, _ := ret[0].([]*entity.BillingConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllActiveMonthly indicates an expected call of ListAllActiveMonthly.
func (mr *MockBillingConfigRepositoryMockRecorder) ListAllActiveMonthly(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllActiveMonthly", reflect.TypeOf((*MockBillingConfigRepository)(nil).ListAllActiveMonthly), ctx)
}

// Update mocks base method.
func (m *MockBillingConfigRepository) Update(ctx context.Context, config *entity.BillingConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBillingConfigRepositoryMockRecorder) Update(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBillingConfigRepository)(nil).Update), ctx, config)
}
