// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/invoice_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/invoice_repository.go -destination=internal/domain/mocks/invoice_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/finance-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockInvoiceRepository is a mock of InvoiceRepository interface.
type MockInvoiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceRepositoryMockRecorder
	isgomock struct{}
}

// MockInvoiceRepositoryMockRecorder is the mock recorder for MockInvoiceRepository.
type MockInvoiceRepositoryMockRecorder struct {
	mock *MockInvoiceRepository
}

// NewMockInvoiceRepository creates a new mock instance.
func NewMockInvoiceRepository(ctrl *gomock.Controller) *MockInvoiceRepository {
	mock := &MockInvoiceRepository{ctrl: ctrl}
	mock.recorder = &MockInvoiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceRepository) EXPECT() *MockInvoiceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInvoiceRepository) Create(ctx context.Context, invoice *entity.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockInvoiceRepositoryMockRecorder) Create(ctx, invoice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvoiceRepository)(nil).Create), ctx, invoice)
}

// GetByID mocks base method.
func (m *MockInvoiceRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockInvoiceRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockInvoiceRepository)(nil).GetByID), ctx, id)
}

// GetByInvoiceNumber mocks base method.
func (m *MockInvoiceRepository) GetByInvoiceNumber(ctx context.Context, invoiceNumber string) (*entity.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByInvoiceNumber", ctx, invoiceNumber)
	ret0, _ := ret[0].(*entity.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByInvoiceNumber indicates an expected call of GetByInvoiceNumber.
func (mr *MockInvoiceRepositoryMockRecorder) GetByInvoiceNumber(ctx, invoiceNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByInvoiceNumber", reflect.TypeOf((*MockInvoiceRepository)(nil).GetByInvoiceNumber), ctx, invoiceNumber)
}

// List mocks base method.
func (m *MockInvoiceRepository) List(ctx context.Context, tenantID, studentID uuid.UUID, status entity.InvoiceStatus) ([]*entity.Invoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID, studentID, status)
	ret0, _ := ret[0].([]*entity.Invoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInvoiceRepositoryMockRecorder) List(ctx, tenantID, studentID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInvoiceRepository)(nil).List), ctx, tenantID, studentID, status)
}

// Update mocks base method.
func (m *MockInvoiceRepository) Update(ctx context.Context, invoice *entity.Invoice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, invoice)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInvoiceRepositoryMockRecorder) Update(ctx, invoice any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInvoiceRepository)(nil).Update), ctx, invoice)
}
