// Code generated by MockGen. DO NOT EDIT.
// Source: services/finance-service/internal/domain/repository/report_repository.go
//
// Generated by this command:
//
//	mockgen -source=services/finance-service/internal/domain/repository/report_repository.go -destination=services/finance-service/internal/domain/mocks/report_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	entity "github.com/jjaenal/sisfo-akademik-backend/services/finance-service/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockReportRepository is a mock of ReportRepository interface.
type MockReportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReportRepositoryMockRecorder
	isgomock struct{}
}

// MockReportRepositoryMockRecorder is the mock recorder for MockReportRepository.
type MockReportRepositoryMockRecorder struct {
	mock *MockReportRepository
}

// NewMockReportRepository creates a new mock instance.
func NewMockReportRepository(ctrl *gomock.Controller) *MockReportRepository {
	mock := &MockReportRepository{ctrl: ctrl}
	mock.recorder = &MockReportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportRepository) EXPECT() *MockReportRepositoryMockRecorder {
	return m.recorder
}

// GetDailyRevenue mocks base method.
func (m *MockReportRepository) GetDailyRevenue(ctx context.Context, tenantID uuid.UUID, startDate, endDate time.Time) ([]*entity.DailyRevenue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyRevenue", ctx, tenantID, startDate, endDate)
	ret0, _ := ret[0].([]*entity.DailyRevenue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyRevenue indicates an expected call of GetDailyRevenue.
func (mr *MockReportRepositoryMockRecorder) GetDailyRevenue(ctx, tenantID, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyRevenue", reflect.TypeOf((*MockReportRepository)(nil).GetDailyRevenue), ctx, tenantID, startDate, endDate)
}

// GetMonthlyRevenue mocks base method.
func (m *MockReportRepository) GetMonthlyRevenue(ctx context.Context, tenantID uuid.UUID, year int) ([]*entity.MonthlyRevenue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonthlyRevenue", ctx, tenantID, year)
	ret0, _ := ret[0].([]*entity.MonthlyRevenue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonthlyRevenue indicates an expected call of GetMonthlyRevenue.
func (mr *MockReportRepositoryMockRecorder) GetMonthlyRevenue(ctx, tenantID, year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonthlyRevenue", reflect.TypeOf((*MockReportRepository)(nil).GetMonthlyRevenue), ctx, tenantID, year)
}

// GetOutstandingInvoices mocks base method.
func (m *MockReportRepository) GetOutstandingInvoices(ctx context.Context, tenantID uuid.UUID) ([]*entity.OutstandingReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutstandingInvoices", ctx, tenantID)
	ret0, _ := ret[0].([]*entity.OutstandingReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutstandingInvoices indicates an expected call of GetOutstandingInvoices.
func (mr *MockReportRepositoryMockRecorder) GetOutstandingInvoices(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutstandingInvoices", reflect.TypeOf((*MockReportRepository)(nil).GetOutstandingInvoices), ctx, tenantID)
}
